### ISSUE TITLE
Functional Tests: COPPA Sign Up tests fail if local testrunner timezone is a day behind the browser timezone

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#1768]
Running `npm run test-latest` locally at 10PM EST (tests pass after midnight) gives me this error:
 
```
Running: sign_up
Test main - sign_up - select an age that is one day too young FAILED on firefox 32.0.3 on LINUX:
CancelError: Timeout reached on main - sign_up - select an age that is one day too young
Error: Timeout reached on main - sign_up - select an age that is one day too young
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Test main - sign_up - select a 13 year old, on their birthday FAILED on firefox 32.0.3 on LINUX:
CancelError: Timeout reached on main - sign_up - select a 13 year old, on their birthday
Error: Timeout reached on main - sign_up - select a 13 year old, on their birthday
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Running: complete_sign_up
```

**Comment by vladikoff** [comment]
We don't use Sauce for this anymore, so this is not a problem
