### ISSUE TITLE
COPPA tests failing on Travis

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2015]
This started happening once we hit 2015. Not sure what the cause of this is yet.
Example build: https://travis-ci.org/mozilla/fxa-content-server/builds/45908339

```
GET /sessionToken/dcc624b0cd3d90f2ba2df9b1224c6c9b30637ac853b9252e1e2fa141da57a753
Test main - sign_up - select an age that is one day too young FAILED on firefox 34.0 on LINUX:
CancelError: Timeout reached on main - sign_up - select an age that is one day too young
Error: Timeout reached on main - sign_up - select an age that is one day too young
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Test main - sign_up - select a 13 year old, on their birthday FAILED on firefox 34.0 on LINUX:
StaleElementReference: [POST http://localhost:4444/wd/hub/session/1556a743-24f4-40a2-ab21-a092e1edf273/element/163/click] Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'testing-worker-linux-11-1-31038-linux-6-45908340', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-042stab090.5', java.version: '1.7.0_72'
Driver info: driver.version: unknown
  at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:68:9>
  at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
  at Element._post  <node_modules/intern-geezer/node_modules/leadfoot/Element.js:20:31>
  at Element.click  <node_modules/intern-geezer/node_modules/leadfoot/Element.js:135:15>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:662:19>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/home/travis/build/mozilla/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.methods.click  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:345:34>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:202:12>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:203:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/home/travis/build/mozilla/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:205:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/home/travis/build/mozilla/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.methods.click  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:345:34>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:206:12>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:207:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/home/travis/build/mozilla/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:210:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) [as getVisibleText] (/home/travis/build/mozilla/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:211:12>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:212:12>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.select a 13 year old, on their birthday [as test]  <tests/functional/sign_up.js:216:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
404 '/emailRecord/7369676e696e302e34313537393934393632323937333840726573746d61696c2e6e6574'
PUT /account/13961a3040544d0a9df745f1ec9de0ac
PUT /sessionToken/7faf283eba1c17c2b6033857998a08962dbf4106f90e0e94ea59e93d7c5954f3
04:18:49.539Z ERROR fxa-auth-server:  (op=Notifier.publish)
    err: {
      "message": "Missing region in config",
      "code": "ConfigError",
      "time": "2015-01-05T04:18:49.539Z"
    }
```

**Comment by shane-tomlinson** [comment]
Does this have anything to do with #1768?

**Comment by shane-tomlinson** [comment]
I see the problem. We are not handling year wrapping correctly on Jan 1st.

**Comment by shane-tomlinson** [comment]
@vladikoff - you fixed this, right?
