### ISSUE TITLE
functional tests fail locally in Chrome

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2029]
> Test main - sign_up - sign up with email with leading whitespace on the email FAILED on chrome 37.0.2062.122 on MAC:
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/2781b736-5a1d-4cfe-a77b-1118c6488977/element/146/click] element not visible
  (Session info: chrome=37.0.2062.122)
  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.10.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'Shanes-Retina-MBP.local', ip: '192.168.1.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.1', java.version: '1.7.0_40'
Session ID: 6896b973534beaae76198367c55234cf
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/x6/zd3bzsyd08v932ymg7t283rc0000gn/T/.org.chromium.Chromium.uZBsQb}, rotatable=false, locationContextEnabled=true, version=37.0.2062.122, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
  at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:68:9>
  at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
  at Element._post  <node_modules/intern-geezer/node_modules/leadfoot/Element.js:20:31>
  at Element.click  <node_modules/intern-geezer/node_modules/leadfoot/Element.js:135:15>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:662:19>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
  at processImmediate [as _immediateCallback]  <timers.js:330:15>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.methods.click  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:345:34>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:297:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) [as clearValue] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:298:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.type  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:60:73>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:299:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:300:8>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:302:8>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.methods.click  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:345:34>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:303:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) [as clearValue] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:304:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.type  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:60:73>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:305:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:306:8>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:308:8>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.methods.click  <node_modules/intern-geezer/node_modules/leadfoot/compat.js:345:34>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:309:10>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:310:8>
  at fillOutSignIn  <tests/functional/sign_up.js:33:30>
  at CompatCommand.<anonymous>  <tests/functional/sign_up.js:76:18>
  at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.sign up with email with leading whitespace on the email [as test]  <tests/functional/sign_up.js:75:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findById] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.sign up with email with leading whitespace on the email [as test]  <tests/functional/sign_up.js:80:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.sign up with email with leading whitespace on the email [as test]  <tests/functional/sign_up.js:81:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>

**Comment by shane-tomlinson** [comment]
Closing until we fix it.
