### ISSUE TITLE
oauth sign up test for bounced email fails when run locally

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2053]
## STR
1. Check out master
1. Run the oauth functional tests locally
1. Watch the following test always fail

> Waiting for email at: http://127.0.0.1:9001/mail/signin0.7176071112044156
> Test main - oauth sign up - sign up, bounce email, allow user to restart flow but force a different email FAILED on firefox 34.0.5 on MAC:
CancelError: Timeout reached on main - oauth sign up - sign up, bounce email, allow user to restart flow but force a different email
Error: Timeout reached on main - oauth sign up - sign up, bounce email, allow user to restart flow but force a different email
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:110:15>

**Comment by shane-tomlinson** [comment]
False alarm, it's because I modified my auth server to introduce a delay in the email verification loop.

Closing as developer error.
