### ISSUE TITLE
tests.dev.lcip.org selenium tests not working

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2110]
Tests are failing to start. The selenium daemon at :4444 doesn't seem to be responding

```
[18:33:41][Step 1/1] tos-pp#636f734ff8 app/bower_components/tos-pp
[18:33:42][Step 1/1] Creating Firefox profile...
[18:33:43][Step 1/1] Listening on 0.0.0.0:9090
[18:33:43][Step 1/1] Starting tunnel...
[18:35:50][Step 1/1] 
[18:35:50][Step 1/1] Error: connect ETIMEDOUT
[18:35:50][Step 1/1]   at errnoException  <net.js:905:11>
[18:35:50][Step 1/1]   at Object.afterConnect [as oncomplete]  <net.js:896:19>
[18:35:50][Step 1/1] TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
[18:35:50][Step 1/1] Process exited with code 1
[18:35:50][Step 1/1] Step Run Tests (Command Line) failed
```

**Comment by vladikoff** [comment]
Fixed this up and restarted the tests. Also added a better security policy for the selenium hub
