### ISSUE TITLE
[esr] firefox 31.6.0 on LINUX: 5/54 tests failed (all iframe oauth channel tests)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2300]
I'm a little surprised that we pass on Fx 18, but not on the most recent ESR, but this is the result I'm getting. 

```
Waiting for email at: http://restmail.net/mail/signin0.36518820421770215
Waiting for email at: http://restmail.net/mail/signin0.36518820421770215
Running: preverified oauth sign up
Running: iframe oauth channel
Test main - iframe oauth channel - signup, verify same browser FAILED on firefox 31.6.0 on LINUX:
CancelError: Timeout reached on main - iframe oauth channel - signup, verify same browser
Error: Timeout reached on main - iframe oauth channel - signup, verify same browser
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Test main - iframe oauth channel - signup, verify same browser with original tab closed FAILED on firefox 31.6.0 on LINUX:
CancelError: Timeout reached on main - iframe oauth channel - signup, verify same browser with original tab closed
Error: Timeout reached on main - iframe oauth channel - signup, verify same browser with original tab closed
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Test main - iframe oauth channel - signup, verify same browser by replacing the original tab FAILED on firefox 31.6.0 on LINUX:
CancelError: Timeout reached on main - iframe oauth channel - signup, verify same browser by replacing the original tab
Error: Timeout reached on main - iframe oauth channel - signup, verify same browser by replacing the original tab
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Test main - iframe oauth channel - signup, verify different browser - from original tab's P.O.V. FAILED on firefox 31.6.0 on LINUX:
CancelError: Timeout reached on main - iframe oauth channel - signup, verify different browser - from original tab's P.O.V.
Error: Timeout reached on main - iframe oauth channel - signup, verify different browser - from original tab's P.O.V.
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Test main - iframe oauth channel - signup, verify different browser - from new browser's P.O.V. FAILED on firefox 31.6.0 on LINUX:
CancelError: Timeout reached on main - iframe oauth channel - signup, verify different browser - from new browser's P.O.V.
Error: Timeout reached on main - iframe oauth channel - signup, verify different browser - from new browser's P.O.V.
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Waiting for email at: http://restmail.net/mail/signin0.14890368073247373
Waiting for email at: http://restmail.net/mail/signin0.14890368073247373
Waiting for email at: http://restmail.net/mail/signin0.17042423621751368
Waiting for email at: http://restmail.net/mail/signin0.17042423621751368
Waiting for email at: http://restmail.net/mail/signin0.31897587422281504
Waiting for email at: http://restmail.net/mail/signin0.31897587422281504
Waiting for email at: http://restmail.net/mail/signin0.703977984841913
Waiting for email at: http://restmail.net/mail/signin0.703977984841913
Waiting for email at: http://restmail.net/mail/signin0.22882285877130926
Running: oauth force_auth with a registered force_email
Running: oauth force_auth with an unregistered force_mail
No unit test coverage for firefox 31.6.0 on LINUX
firefox 31.6.0 on LINUX: 5/54 tests failed

TOTAL: tested 1 platforms, 5/54 tests failed
```

**Comment by vladikoff** [comment]
`5/54 tests failed`

Why are there only 54 tests I wonder

**Comment by vladikoff** [comment]
Or are these only the oauth tests?

**Comment by jrgm** [comment]
Yeah, only the oauth tests were run this time (was just doing a shortcut run to confirm).

Anyways, I see what's happening: in five places while running the the oauth iframe tests, the 'Sign In' or 'Next' or whichever button to be clicked is partially outside the viewport of the browser. This prevents the click from occuring. If I simply make the browser taller, the tests all pass. Could set the size at startup, or check positions and scroll the button in to view. Actually, a standard size when running tests is perhaps a good practice.

**Comment by vladikoff** [comment]
Seems like a Selenium FirefoxDriver side-effect / bug. I think normally the webdriver should be able to find things that are not in the view.

**Comment by jrgm** [comment]
This has appeared to have mostly solved its own geometry issues. Closing.
