### ISSUE TITLE
OAuth permissions failing on TeamCity

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2404]
See http://tests.dev.lcip.org:8111/viewType.html?buildTypeId=FxaLatest_FunctionalTests
```
[Step 1/1] Running: oauth permissions
[13:53:27][Step 1/1] NoSuchElement: [POST http://localhost:4444/wd/hub/session/8ce8f94c-0c0e-4dba-afe9-c81bfcbcc003/element / {"using":"css selector","value":"#footer-main"}] Unable to locate element: {"method":"css selector","selector":"#footer-main"}
[13:53:27][Step 1/1] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[13:53:27][Step 1/1] Build info: version: '2.45.0', revision: 'a53b301', time: '2015-04-06 21:57:50'
[13:53:27][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[13:53:27][Step 1/1] Driver info: driver.version: unknown
[13:53:27][Step 1/1]   at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:62:9>
[13:53:27][Step 1/1]   at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
[13:53:27][Step 1/1]   at ProxiedSession.Session.find  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:1051:15>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:41:36>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[13:53:27][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[13:53:27][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
[13:53:27][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:354:15>
[13:53:27][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:199:14>
[13:53:27][Step 1/1]   at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
[13:53:27][Step 1/1]   at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
[13:53:27][Step 1/1]   at clear123DoneState  <tests/functional/lib/helpers.js:117:8>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <tests/functional/lib/helpers.js:57:18>
[13:53:27][Step 1/1]   at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[13:53:27][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[13:53:27][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:199:14>
[13:53:27][Step 1/1]   at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
[13:53:27][Step 1/1]   at clear123DoneState  <tests/functional/lib/helpers.js:118:8>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <tests/functional/lib/helpers.js:57:18>
[13:53:27][Step 1/1]   at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[13:53:27][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[13:53:27][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
[13:53:27][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:199:14>
[13:53:27][Step 1/1]   at <CompatCommand.target.(anonymous function) [as execute] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/leadfoot/Command.js:592:11)>
[13:53:27][Step 1/1]   at clear123DoneState  <tests/functional/lib/helpers.js:120:8>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <tests/functional/lib/helpers.js:57:18>
[13:53:27][Step 1/1]   at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[13:53:27][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[13:53:27][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
[13:53:27][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:199:14>
[13:53:27][Step 1/1]   at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
[13:53:27][Step 1/1]   at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
[13:53:27][Step 1/1]   at clear123DoneState  <tests/functional/lib/helpers.js:127:8>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <tests/functional/lib/helpers.js:57:18>
[13:53:27][Step 1/1]   at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[13:53:27][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[13:53:27][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:199:14>
[13:53:27][Step 1/1]   at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
[13:53:27][Step 1/1]   at clear123DoneState  <tests/functional/lib/helpers.js:128:8>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <tests/functional/lib/helpers.js:57:18>
[13:53:27][Step 1/1]   at runCallback  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:509:31>
[13:53:27][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:526:11>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[13:53:27][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[13:53:27][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[13:53:27][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
[13:53:27][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:199:14>
[13:53:27][Step 1/1]   at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
[13:53:27][Step 1/1]   at Object.clearBrowserState  <tests/functional/lib/helpers.js:55:8>
[13:53:27][Step 1/1]   at registerSuite.beforeEach  <tests/functional/oauth_permissions.js:39:32>
[13:53:27][Step 1/1]   at <target.(anonymous function).dispatcher [as beforeEach] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/dojo/aspect.js:102:31)>
[13:53:27][Step 1/1]   at callOnSuite  <node_modules/intern-geezer/lib/Suite.js:126:42>
[13:53:27][Step 1/1]   at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:160:8>
[13:53:27][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[13:53:27][Step 1/1]   at Promise.then.promise.then  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:258:5>
[13:53:27][Step 1/1]   at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:163:10>
```

**Comment by vladikoff** [comment]
Fixed by adding `fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ ` to config.
