### ISSUE TITLE
OAuth web channel keys functional tests failing 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2407]
`oauth web channel keys - signup, verify same browser, in a different tab, with original tab`
Getting these failures locally and TeamCity:

![image](https://cloud.githubusercontent.com/assets/128755/7615839/34d55f98-f96e-11e4-8ff5-b2de5e2d8d1b.png)

![image](https://cloud.githubusercontent.com/assets/128755/7615977/2211fa14-f96f-11e4-9492-dbaeac0c9788.png)

**Comment by vladikoff** [comment]
```
Test main - oauth web channel keys - password reset, verify same browser FAILED on firefox 37.0.2 on MAC:
CancelError: Timeout reached on main - oauth web channel keys - password reset, verify same browser
Error: Timeout reached on main - oauth web channel keys - password reset, verify same browser
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
```

![image](https://cloud.githubusercontent.com/assets/128755/7616018/6cb1cf04-f96f-11e4-9d40-f7851ef13669.png)

**Comment by shane-tomlinson** [comment]
cc @rfk - the look to me like the timing problems that you feared could happen.

**Comment by vladikoff** [comment]
```
Test main - oauth web channel keys - password reset, verify in different browser, from the original tab's P.O.V. FAILED on firefox 37.0.2 on MAC:
CancelError: Timeout reached on main - oauth web channel keys - password reset, verify in different browser, from the original tab's P.O.V.
Error: Timeout reached on main - oauth web channel keys - password reset, verify in different browser, from the original tab's P.O.V.
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
```

**Comment by vladikoff** [comment]
```
Test main - oauth web channel keys - signin a verified account and requesting keys after signing in to sync FAILED on firefox 37.0.2 on MAC:
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/145b85fe-2b77-4a19-9e72-5a7d55e44a13/element/666/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Vlads-MacBook-Pro.local', ip: '10.242.29.24', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
//// removed stack trace .....
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:397:10>
  at CompatCommand.self.get.get.setFindTimeout.execute.findByCssSelector.end.then.then.testIsBrowserNotifiedOfSyncLogin.checkVerified  <tests/functional/oauth_webchannel_keys.js:401:40>
```

**Comment by vladikoff** [comment]
I fixed this locally but still happens in TeamCity. Investigating....

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/fxa-content-server/issues/2410
