### ISSUE TITLE
permissions screen tests failing on latest (not locally)

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2414]
STR

1. Update tests/functional_oauth.js to only run `oauth_permissions`
1. Run this command:
```
node_modules/.bin/intern-runner config=tests/intern_functional_oauth fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaEmailRoot=http://restmail.net fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaIframeOauthApp=https://123done-latest.dev.lcip.org/iframe fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ fxaProduction=true fxaToken=https://token.dev.lcip.org/1.0/sync/1.5
```

Results:
```
Creating Firefox profile...
Listening on 0.0.0.0:9090
Starting tunnel...
Initialised firefox 37.0.2 on MAC
Running: main
Running: oauth permissions
Test main - oauth permissions - re-sign in verified FAILED on firefox 37.0.2 on MAC:
CancelError: Timeout reached on main - oauth permissions - re-sign in verified
Error: Timeout reached on main - oauth permissions - re-sign in verified
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:110:15>
No unit test coverage for firefox 37.0.2 on MAC
firefox 37.0.2 on MAC: 1/1 tests failed

TOTAL: tested 1 platforms, 1/1 tests failed
```

**Comment by vladikoff** [comment]
```
Running: oauth permissions
Waiting for email at: http://restmail.net/mail/signin0.9369197585619986
Waiting for email at: http://restmail.net/mail/signin0.9369197585619986
Waiting for email at: http://restmail.net/mail/signin0.22735023661516607
Waiting for email at: http://restmail.net/mail/signin0.22735023661516607
Waiting for email at: http://restmail.net/mail/signin0.12336707930080593
Waiting for email at: http://restmail.net/mail/signin0.12336707930080593
No unit test coverage for firefox 37.0.2 on MAC
```
Worked for me against latest.

**Comment by vladikoff** [comment]
Maybe https://321done-latest.dev.lcip.org/ was restarting?

**Comment by vladikoff** [comment]
Also passing on TeamCity: http://tests.dev.lcip.org:8111/viewLog.html?buildId=2470&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog

**Comment by shane-tomlinson** [comment]
huh, it was pretty consistent with #2410 applied.
