### ISSUE TITLE
Unable to Sign In after Sign out on latest.dev

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2511]
It's consistently showing these two failures, and the aborts on a TypeError

```
[22:31:29][Step 1/1] Test main - sign_in - sign in unverified FAILED on firefox 38.0 on LINUX:
[22:31:59][Step 1/1] Test main - sign_in - sign in verified with correct password FAILED on firefox 38.0 on LINUX:
[22:32:35][Step 1/1] TypeError: Cannot read property 'cancel' of undefined
```

```
[22:30:46][Step 1/1] Creating Firefox profile...
[22:30:48][Step 1/1] Listening on 0.0.0.0:9090
[22:30:48][Step 1/1] Starting tunnel...
[22:30:55][Step 1/1] Initialised firefox 38.0 on LINUX
[22:30:55][Step 1/1] Running: main
[22:30:55][Step 1/1] Running: refreshing a screen logs a refresh event
[22:30:58][Step 1/1] Running: sign_in
[22:31:29][Step 1/1] Test main - sign_in - sign in unverified FAILED on firefox 38.0 on LINUX:
[22:31:29][Step 1/1] NoSuchElement: [POST http://localhost:4444/wd/hub/session/09b85d44-87f2-4ab6-8f63-dde7b500a44b/element / {"using":"css selector","value":".verification-email-message"}] Unable to locate element: {"method":"css selector","selector":".verification-email-message"}
[22:31:29][Step 1/1] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[22:31:29][Step 1/1] Build info: version: '2.45.0', revision: 'a53b301', time: '2015-04-06 21:57:50'
[22:31:29][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[22:31:29][Step 1/1] Driver info: driver.version: unknown
[22:31:29][Step 1/1]   at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:68:9>
[22:31:29][Step 1/1]   at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
[22:31:29][Step 1/1]   at ProxiedSession.Session.find  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:1053:15>
[22:31:29][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:41:36>
[22:31:29][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[22:31:29][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[22:31:29][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[22:31:29][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
[22:31:29][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:354:15>
[22:31:29][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
[22:31:29][Step 1/1]   at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
[22:31:29][Step 1/1]   at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
[22:31:29][Step 1/1]   at registerSuite.sign in unverified [as test]  <tests/functional/sign_in.js:63:10>
[22:31:29][Step 1/1]   at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
[22:31:29][Step 1/1]   at <node_modules/intern-geezer/lib/Suite.js:232:13>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1]   at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
[22:31:29][Step 1/1]   at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
[22:31:29][Step 1/1]   at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
[22:31:29][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
[22:31:29][Step 1/1]   at <CompatCommand.target.(anonymous function) [as getVisibleText] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
[22:31:29][Step 1/1]   at registerSuite.sign in unverified [as test]  <tests/functional/sign_in.js:64:12>
[22:31:29][Step 1/1]   at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
[22:31:29][Step 1/1]   at <node_modules/intern-geezer/lib/Suite.js:232:13>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1]   at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
[22:31:29][Step 1/1]   at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
[22:31:29][Step 1/1]   at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
[22:31:29][Step 1/1]   at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
[22:31:29][Step 1/1]   at registerSuite.sign in unverified [as test]  <tests/functional/sign_in.js:65:12>
[22:31:29][Step 1/1]   at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
[22:31:29][Step 1/1]   at <node_modules/intern-geezer/lib/Suite.js:232:13>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1]   at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
[22:31:29][Step 1/1]   at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
[22:31:29][Step 1/1]   at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
[22:31:29][Step 1/1]   at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
[22:31:29][Step 1/1]   at registerSuite.sign in unverified [as test]  <tests/functional/sign_in.js:69:10>
[22:31:29][Step 1/1]   at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
[22:31:29][Step 1/1]   at <node_modules/intern-geezer/lib/Suite.js:232:13>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1]   at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
[22:31:29][Step 1/1]   at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
[22:31:29][Step 1/1]   at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
[22:31:29][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:29][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.5736312475055456
[22:31:59][Step 1/1] Test main - sign_in - sign in verified with correct password FAILED on firefox 38.0 on LINUX:
[22:31:59][Step 1/1] NoSuchElement: [POST http://localhost:4444/wd/hub/session/09b85d44-87f2-4ab6-8f63-dde7b500a44b/element / {"using":"id","value":"fxa-settings-header"}] Unable to locate element: {"method":"id","selector":"fxa-settings-header"}
[22:31:59][Step 1/1] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[22:31:59][Step 1/1] Build info: version: '2.45.0', revision: 'a53b301', time: '2015-04-06 21:57:50'
[22:31:59][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[22:31:59][Step 1/1] Driver info: driver.version: unknown
[22:31:59][Step 1/1]   at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:68:9>
[22:31:59][Step 1/1]   at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
[22:31:59][Step 1/1]   at ProxiedSession.Session.find  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:1053:15>
[22:31:59][Step 1/1]   at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:41:36>
[22:31:59][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
[22:31:59][Step 1/1]   at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
[22:31:59][Step 1/1]   at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
[22:31:59][Step 1/1]   at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
[22:31:59][Step 1/1]   at processImmediate [as _immediateCallback]  <timers.js:354:15>
[22:31:59][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
[22:31:59][Step 1/1]   at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
[22:31:59][Step 1/1]   at <CompatCommand.prototype.(anonymous function) [as findById] (/home/ubuntu/TeamCity/buildAgent/work/f93452fdf52dbc98/fxa-content-server-latest/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
[22:31:59][Step 1/1]   at <tests/functional/sign_in.js:78:14>
[22:31:59][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:59][Step 1/1]   at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
[22:31:59][Step 1/1]   at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
[22:31:59][Step 1/1]   at signalDeferred  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:81:15>
[22:31:59][Step 1/1]   at <node_modules/intern-geezer/node_modules/dojo/Deferred.js:70:4>
[22:31:59][Step 1/1]   at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1317:9>
[22:31:59][Step 1/1]   at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
[22:31:59][Step 1/1]   at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
[22:31:59][Step 1/1]   at <tests/functional/sign_in.js:79:14>
[22:31:59][Step 1/1]   at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
[22:31:59][Step 1/1]   at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
[22:31:59][Step 1/1]   at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
[22:31:59][Step 1/1]   at signalDeferred  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:81:15>
[22:31:59][Step 1/1]   at <node_modules/intern-geezer/node_modules/dojo/Deferred.js:70:4>
[22:31:59][Step 1/1]   at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1317:9>
[22:31:59][Step 1/1]   at Object.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1024:6>
[22:31:59][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.5736312475055456
[22:32:05][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.5736312475055456
[22:32:35][Step 1/1] TypeError: Cannot read property 'cancel' of undefined
[22:32:35][Step 1/1]   at Array.Command.cancel  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:559:16>
[22:32:35][Step 1/1]   at <node_modules/intern-geezer/node_modules/dojo/Deferred.js:255:40>
[22:32:35][Step 1/1]   at Promise.cancel.promise.cancel  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:286:27>
[22:32:35][Step 1/1]   at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:31>
[22:32:35][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
[22:32:35][Step 1/1] Process exited with code 1
[22:32:35][Step 1/1] Step Run Tests (Command Line) failed
```

**Comment by vladikoff** [comment]
@jrgm not the content server fault.

If you manually create an account on latest.dev.lcip.org with some password then signout and try to sign in you get "incorrect password". 
Are we missing some sql changes?

@dannycoates @chilts help!

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/7961402/671eddae-09d5-11e5-8772-fe3549d41ac6.png)

**Comment by jrgm** [comment]
Yeah, untangling this now. Problem in the patching task. d

**Comment by vladikoff** [comment]
Thanks @jrgm!

**Comment by jrgm** [comment]
Actually this can be reproduce locally if running fxa-auth-db-mysql with a real database.

**Comment by jrgm** [comment]
Okay, if I revert this change to neuter the new password changes, I can re-login again.

https://github.com/mozilla/fxa-auth-server/pull/943/files#diff-bab7d1308b32400b6848399d1cdbdfebL20

**Comment by pdehaan** [comment]
Closing per @jrgm's comment in IRC:

> @pdehaan> @jrgm: still an issue, or fixed w/ partial revert? https://github.com/mozilla/fxa-content-server/issues/2511
> @jrgm> @pdehaan: so you can close #2511 as fixed by the workaround. Real fix is pending here https://github.com/mozilla/fxa-auth-db-mysql/pull/50
