### ISSUE TITLE
OAuth preverified sign up functional test intermittent failure

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2541]
```
Running: preverified oauth sign up
Test main - preverified oauth sign up - preverified sign up FAILED on firefox 37.0.2 on MAC:
NoSuchElement: [POST http://localhost:4444/wd/hub/session/0ccb9ac9-5a09-44f4-980f-977eb719f1e2/element / {"using":"css selector","value":"#footer-main"}] Unable to locate element: {"method":"css selector","selector":"#footer-main"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: 'a53b301', time: '2015-04-06 21:57:50'
System info: host: 'Shanes-Retina-MBP.local', ip: '192.168.1.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_31'
Driver info: driver.version: unknown
  at Server._post  <node_modules/intern-geezer/node_modules/leadfoot/Server.js:68:9>
  at ProxiedSession._post  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:57:30>
  at ProxiedSession.Session.find  <node_modules/intern-geezer/node_modules/leadfoot/Session.js:1053:15>
  at CompatCommand.<anonymous>  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:41:36>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:256:37>
  at runCallbacks  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:13:18>
  at <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:204:17>
  at Object.run [as _onImmediate]  <node_modules/intern-geezer/node_modules/leadfoot/node_modules/dojo/Promise.js:143:29>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:75:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:76:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:79:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:80:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.find  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/lib/strategies.js:24:16)>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:82:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at <CompatCommand.target.(anonymous function) [as getVisibleText] (/Users/stomlinson/development/fxa-content-server/node_modules/intern-geezer/node_modules/leadfoot/Command.js:656:11)>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:83:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.then  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:525:10>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:84:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern-geezer/runner.js:212:14>
  at CompatCommand.Command.end  <node_modules/intern-geezer/node_modules/leadfoot/Command.js:475:10>
  at registerSuite.preverified sign up [as test]  <tests/functional/oauth_preverified_sign_up.js:88:10>
  at declare.run  <node_modules/intern-geezer/lib/Test.js:166:19>
  at <node_modules/intern-geezer/lib/Suite.js:232:13>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern-geezer/lib/Suite.js:196:50>
  at signalListener  <node_modules/intern-geezer/node_modules/dojo/Deferred.js:37:21>
```

**Comment by vladikoff** [comment]
Are you getting this locally (which command?)

**Comment by shane-tomlinson** [comment]
@vladikoff - local, `npm run-script test-functional-oauth`

**Comment by vladikoff** [comment]
@shane-tomlinson did you update from iframe_allowed_origins to allowed_parent_origins ?

**Comment by vladikoff** [comment]
in the local.json-dist thingy

**Comment by shane-tomlinson** [comment]
I'm no longer able to reproduce this. Closing.
