### ISSUE TITLE
EHTTP Status code of 401

### ISSUE THREAD

**Issue by tuaris** [mozilla/fxa-content-server#2605]
Trying to install this on FreeBSD 10.1 but I am getting this error:

```
\
> intern@3.0.0-pre install /usr/local/fxasycn/fxa-content-server/node_modules/intern
> node support/fixdeps.js


> fxa-content-server@0.39.0 postinstall /usr/local/fxasycn/fxa-content-server
> bower update --config.interactive=false -s

bower sinon#*                    EHTTP Status code of 401

npm ERR! FreeBSD 10.1-RELEASE-p10
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.38
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! fxa-content-server@0.39.0 postinstall: `bower update --config.interactive=false -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fxa-content-server@0.39.0 postinstall script 'bower update --config.interactive=false -s'.
npm ERR! This is most likely a problem with the fxa-content-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower update --config.interactive=false -s
npm ERR! You can get their info via:
npm ERR!     npm owner ls fxa-content-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/fxasycn/fxa-content-server/npm-debug.log
```

Verbose output

```
bower sinon#*                    EHTTP Status code of 401

Stack trace:
Error: Status code of 401
    at createError (/usr/local/fxasycn/fxa-content-server/node_modules/bower/lib/util/createError.js:4:15)
    at Request.<anonymous> (/usr/local/fxasycn/fxa-content-server/node_modules/bower/lib/util/download.js:45:40)
    at Request.emit (events.js:117:20)
    at Request.onRequestResponse (/usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/request/request.js:1176:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData [as ondata] (http.js:1584:20)
    at TCP.onread (net.js:528:27)

Console trace:
Error
    at StandardRenderer.error (/usr/local/fxasycn/fxa-content-server/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/fxasycn/fxa-content-server/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/fxasycn/fxa-content-server/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/fxasycn/fxa-content-server/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.38
OS: FreeBSD 10.1-RELEASE-p10 x64
```

**Comment by tuaris** [comment]
Also got the same result when going through the install of [fxa-local-dev](https://github.com/mozilla/fxa-local-dev)

**Comment by vladikoff** [comment]
@tuaris something is blocking your connection during `bower install`

If you are in the content server directory: 

`npm install bower`

`node_modules/.bin/bower install sinon` 
then should return 
```
➜  dev  bower install sinon
bower not-cached    git://github.com/cjohansen/Sinon.JS.git#*
bower resolve       git://github.com/cjohansen/Sinon.JS.git#*
bower download      https://github.com/cjohansen/Sinon.JS/archive/v1.15.3.tar.gz
bower extract       sinon#* archive.tar.gz
bower invalid-meta  sinon is missing "main" entry in bower.json
bower invalid-meta  sinon is missing "ignore" entry in bower.json
bower resolved      git://github.com/cjohansen/Sinon.JS.git#1.15.3
bower install       sinon#1.15.3
```

Once ` bower install sinon` stops responding with 401s for you then you should fully reinstall the content server.
