### ISSUE TITLE
Locally failing functional test: "sign in with desktop context then no context, desktop credentials should not persist"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2843]
STR

1. Run `npm run test-functional grep="desktop credentials should not persist"`

I have just had 6 consecutive failures, then one pass, then more failures.

Error log:
```
× firefox on any platform - sign in cached - sign in with desktop context then no context, desktop credentials should not persist (2.385s)
AssertionError: expected false to be truthy
  at Assertion.<anonymous>  <node_modules/intern/node_modules/chai/chai.js:532:10>
  at Assertion.Object.defineProperty.get  <node_modules/intern/node_modules/chai/chai.js:3515:29>
  at Function.assert.ok  <node_modules/intern/node_modules/chai/chai.js:1990:31>
  at Command.<anonymous>  <tests/functional/sign_in_cached.js:521:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:517:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:534:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:533:10>
  at Test.registerSuite.sign in with desktop context then no context, desktop credentials should not persist [as test]  <tests/functional/sign_in_cached.js:519:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
```

**Comment by shane-tomlinson** [comment]
If I run the entire `sign in cached` suite, all passes.

**Comment by vladikoff** [comment]
Got this too after running it 4 times:
```
➜  fxa-content-server git:(master) npm run test-functional grep="desktop credentials should not persist"

> fxa-content-server@0.42.0 test-functional /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional "grep=desktop credentials should not persist"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (a66a597a-22eb-4bcb-b945-f5799fdf128c)
✓ firefox on any platform - sign in cached - sign in with desktop context then no context, desktop credentials should not persist (4.881s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/267 tests failed


TOTAL: tested 1 platforms, 0/267 tests failed (266 skipped)
➜  fxa-content-server git:(master) npm run test-functional grep="desktop credentials should not persist"

> fxa-content-server@0.42.0 test-functional /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional "grep=desktop credentials should not persist"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (6ce0d4ee-140e-4099-9030-a2f7e3af0481)
✓ firefox on any platform - sign in cached - sign in with desktop context then no context, desktop credentials should not persist (4.694s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/267 tests failed


TOTAL: tested 1 platforms, 0/267 tests failed (266 skipped)
➜  fxa-content-server git:(master) npm run test-functional grep="desktop credentials should not persist"

> fxa-content-server@0.42.0 test-functional /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional "grep=desktop credentials should not persist"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (5a9102f7-449d-4f3a-b87f-c12ed929e977)
✓ firefox on any platform - sign in cached - sign in with desktop context then no context, desktop credentials should not persist (4.286s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/267 tests failed


TOTAL: tested 1 platforms, 0/267 tests failed (266 skipped)
➜  fxa-content-server git:(master) npm run test-functional grep="desktop credentials should not persist"

> fxa-content-server@0.42.0 test-functional /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional "grep=desktop credentials should not persist"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (b7b41e4d-317e-48f1-813a-69fc879dd747)
× firefox on any platform - sign in cached - sign in with desktop context then no context, desktop credentials should not persist (3.622s)
AssertionError: expected false to be truthy
  at Assertion.<anonymous>  <node_modules/intern/node_modules/chai/chai.js:532:10>
  at Assertion.Object.defineProperty.get  <node_modules/intern/node_modules/chai/chai.js:3515:29>
  at Function.assert.ok  <node_modules/intern/node_modules/chai/chai.js:1990:31>
  at Command.<anonymous>  <tests/functional/sign_in_cached.js:521:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:517:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:534:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:533:10>
  at Test.registerSuite.sign in with desktop context then no context, desktop credentials should not persist [as test]  <tests/functional/sign_in_cached.js:519:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
No unit test coverage for firefox on any platform
firefox on any platform: 1/267 tests failed


TOTAL: tested 1 platforms, 1/267 tests failed (266 skipped)
```
