### ISSUE TITLE
invalid client_id functional tests failing

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2850]
```
➜  fxa-content-server git:(master) npm run test-functional-oauth grep="invalid client_id"

> fxa-content-server@0.42.0 test-functional-oauth /Users/stomlinson/development/fxa-content-server
> intern-runner config=tests/intern_functional_oauth "grep=invalid client_id"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (57b1b242-6de7-44b0-8256-40bfea22e363)
× firefox on any platform - oauth sign in - with invalid client_id (28.754s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/57b1b242-6de7-44b0-8256-40bfea22e363/element / {"using":"css selector","value":"#fxa-400-header"}] Unable to locate element: {"method":"css selector","selector":"#fxa-400-header"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'ShanesRetinaMBP.home', ip: '192.168.1.105', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.8.0_51'
Driver info: driver.version: unknown
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1055:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at Test.registerSuite.with invalid client_id [as test]  <tests/functional/oauth_sign_in.js:85:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
```

I think this was caused by me in #2833

**Comment by shane-tomlinson** [comment]
![screen shot 2015-07-29 at 09 36 40](https://cloud.githubusercontent.com/assets/848085/8953322/65f64d96-35d5-11e5-842a-120d23f20416.png)
