### ISSUE TITLE
flaky test: visit gravatar with gravatar set

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2890]
```
× firefox on any platform - settings/avatar - visit gravatar with gravatar set (30.013s)
CancelError: Timeout reached on firefox on any platform - settings/avatar - visit gravatar with gravatar set
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findById]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at Test.registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:215:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:533:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:557:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
```

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/fxa-content-server/pull/2896
