### ISSUE TITLE
2 failing settings/avatar functional tests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2987]
```
× firefox on any platform - settings/avatar - go to settings with an email NOT selected to see change link should not see one (0.579s)
Error: a.change-avatar should not be present
  at Command.<anonymous>  <tests/functional/lib/helpers.js:196:19>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:195:12>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.go to settings with an email NOT selected to see change link should not see one [as test]  <tests/functional/avatar.js:107:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
× firefox on any platform - settings/avatar - go to settings with an email NOT selected to see change link should not see text link (0.607s)
AssertionError: expected true to be false
  at Assertion.<anonymous>  <node_modules/intern/node_modules/chai/chai.js:572:10>
  at Assertion.Object.defineProperty.get  <node_modules/intern/node_modules/chai/chai.js:3515:29>
  at Function.assert.isFalse  <node_modules/intern/node_modules/chai/chai.js:2204:31>
  at Command.<anonymous>  <tests/functional/avatar.js:122:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.go to settings with an email NOT selected to see change link should not see text link [as test]  <tests/functional/avatar.js:121:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
```

**Comment by shane-tomlinson** [comment]
The Able experiment is set to [enable avatars for everybody on August 12th](https://github.com/mozilla/fxa-content-experiments/blob/dev/avatar-link/avatar-link-visible.js#L6). Either the experiment is wrong and avatars should not be enabled universally, or the functional tests need to be updated.

When avatars are enabled universally and we are sure it'll stay enabled, we should remove the Able choice in the content server and the experiment in Able.
