### ISSUE TITLE
frequent local functional test failure - "opt-in with a plus sign in the email address"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3176]
```
× firefox on any platform - communication preferences - opt-in with a plus sign in the email address (30.016s)
CancelError: Timeout reached on firefox on any platform - communication preferences - opt-in with a plus sign in the email address
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.opt-in with a plus sign in the email address [as test]  <tests/functional/email_opt_in.js:159:12>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
```

**Comment by vladikoff** [comment]
Is that locally or remote? does this use the remote basket server or local fake proxy?

**Comment by shane-tomlinson** [comment]
The "do not opt in to the marketing email" test also fails:
```
× firefox on any platform - communication preferences - do not opt in to the marketing email (30.023s)
CancelError: Timeout reached on firefox on any platform - communication preferences - do not opt in to the marketing email
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.do not opt in to the marketing email [as test]  <tests/functional/email_opt_in.js:215:12>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
```

**Comment by shane-tomlinson** [comment]
local, it fails to open the communication preferences panel.
