### ISSUE TITLE
`latest` functional test failures - checking for `#legal-copy` text

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3182]
```
× firefox on any platform - legal - start at privacy page (0.764s)
AssertionError: expected 0 to be truthy
  at Assertion.<anonymous>  <node_modules/intern/node_modules/chai/chai.js:532:10>
  at Assertion.Object.defineProperty.get  <node_modules/intern/node_modules/chai/chai.js:3515:29>
  at Function.assert.ok  <node_modules/intern/node_modules/chai/chai.js:1990:31>
  at Command.<anonymous>  <tests/functional/legal.js:81:20>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.start at privacy page [as test]  <tests/functional/legal.js:79:12>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
```

**Comment by shane-tomlinson** [comment]
ref #3174
