### ISSUE TITLE
travis failure on reset password tests - Service Unavailable

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3191]
Ref https://travis-ci.org/mozilla/fxa-content-server/jobs/86175523

We have had a string of travis failures on the reset password tests. A conversion of the embedded Base64 encoded image results in:

<img width="772" alt="screen shot 2015-10-19 at 13 53 01" src="https://cloud.githubusercontent.com/assets/848085/10578283/1a6589c6-7669-11e5-95ae-3892d73032c0.png">

I suspected a missing basket proxy server, but if I kill that locally, no problem. I tried to kill the cache and install everything again, which resulted in https://github.com/mozilla/fxa-content-server/issues/3189.

cc @vladikoff, ever see this?

**Comment by shane-tomlinson** [comment]
Looking deeper into the logs, under the `ci/deps.sh` section - https://travis-ci.org/mozilla/fxa-content-server/jobs/86175523#L873

```
fxa-oauth-server.CRITICAL: uncaughtException Error: Cannot find module 'fxa-jwtool'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/node_modules/fxa-oauth-server/lib/routes/token.js:12:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/node_modules/fxa-oauth-server/lib/routing.js:53:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Further down - https://travis-ci.org/mozilla/fxa-content-server/jobs/86175523#L1003

```
../bigint.cc:9:17: fatal error: gmp.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/bigint/bigint.o] Error 1
make: Leaving directory `/home/travis/build/mozilla/fxa-content-server/node_modules/browserid-verifier/node_modules/browserid-local-verify/node_modules/browserid-crypto/node_modules/bigint/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/travis/build/mozilla/fxa-content-server/node_modules/browserid-verifier/node_modules/browserid-local-verify/node_modules/browserid-crypto/node_modules/bigint
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing bigint@0.4.2
```

**Comment by shane-tomlinson** [comment]
Closing here, this is an OAuth server bug.
