### ISSUE TITLE
functional test failure on master: verification_experiments - mailcheck - treatment works

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3236]
× firefox on any platform - verification_experiments - mailcheck - treatment works (29.184s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/decbea02-afd4-4d91-8a75-09bd71aece56/element / {"using":"css selector","value":".tooltip-suggest > span:nth-child(1)"}] Unable to locate element: {"method":"css selector","selector":".tooltip-suggest > span:nth-child(1)"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Shanes-Retina-MBP.local', ip: '192.168.1.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_51'
Driver info: driver.version: unknown
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1055:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at Test.registerSuite.treatment works [as test]  <tests/functional/verification_experiments.js:115:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:363:15>

**Comment by shane-tomlinson** [comment]
fixed by https://github.com/mozilla/fxa-content-experiments/pull/30, closing.
