### ISSUE TITLE
grunt validate-shrinkwrap fails, all travis runs fail

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3237]
This is after blowing away `node_modules` and a fresh npm install:

```bash
➜  fxa-content-server git:(master) grunt validate-shrinkwrap
Running "validate-shrinkwrap" task
/Users/stomlinson/development/fxa-content-server/npm-shrinkwrap.json
fxa-content-server.CRITICAL: uncaughtException TypeError: Cannot read property 'patched_versions' of undefined
    at /Users/stomlinson/development/fxa-content-server/node_modules/grunt-nsp-shrinkwrap/tasks/shrinkwrap.js:47:79
    at Array.forEach (native)
    at Request._callback (/Users/stomlinson/development/fxa-content-server/node_modules/grunt-nsp-shrinkwrap/tasks/shrinkwrap.js:46:26)
    at Request.self.callback (/Users/stomlinson/development/fxa-content-server/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/stomlinson/development/fxa-content-server/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/stomlinson/development/fxa-content-server/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Fatal error: Cannot read property 'patched_versions' of undefined


Execution Time (2015-11-02 11:35:15 UTC)
loading tasks        2.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 28%
validate-shrinkwrap  7.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 72%
Total 9.9s

➜  fxa-content-server git:(master)
```

See https://travis-ci.org/mozilla/fxa-content-server/jobs/88687808#L1185

**Comment by shane-tomlinson** [comment]
grunt-nsp-shrinkwrap has been deprecated:

```
➜  fxa-content-server git:(phil/issue-3024) npm info grunt-nsp-shrinkwrap

{ name: 'grunt-nsp-shrinkwrap',
  description: 'Grunt plugin for Node Security Project npm-shrinkwrap.json validation',
  'dist-tags': { latest: '0.0.3' },
  versions: [ '0.0.1', '0.0.2', '0.0.3' ],
  maintainers: 'adam_baldwin <baldwin@andyet.net>',
  time:
   { modified: '2015-10-31T16:59:24.273Z',
     created: '2014-03-18T04:02:35.808Z',
     '0.0.1': '2014-03-18T04:02:35.808Z',
     '0.0.2': '2014-03-18T04:43:08.554Z',
     '0.0.3': '2014-03-18T16:14:59.128Z' },
  homepage: 'https://nodesecurity.io',
  keywords:
   [ 'nsp',
     'grunt',
     'gruntplugin',
     'shrinkwrap',
     'npm-shrinkwrap.json',
     'security' ],
  author: 'Adam Baldwin',
  license: 'MIT',
  readmeFilename: 'README.md',
  repository:
   { type: 'git',
     url: 'git@github.com:nodesecurity/grunt-nsp-shrinkwrap.git' },
  bugs: { url: 'https://github.com/nodesecurity/grunt-nsp-shrinkwrap/issues/' },
  version: '0.0.3',
  dependencies:
   { 'cli-color': '^0.2.3',
     colors: '^0.6.2',
     grunt: '^0.4.4',
     request: '^2.34.0',
     'text-table': '^0.2.0' },
  devDependencies: { 'precommit-hook': '^0.3.10' },
  main: 'Gruntfile.js',
  scripts: { test: 'echo "Error: no test specified" && exit 0' },
  dist:
   { shasum: '04605dcc7d8c5bbf42d5b1d37a252bdceb1af8ff',
     tarball: 'http://registry.npmjs.org/grunt-nsp-shrinkwrap/-/grunt-nsp-shrinkwrap-0.0.3.tgz' },
  deprecated: 'new api version released, use grunt-nsp instead',
  directories: {} }
```

**Comment by shane-tomlinson** [comment]
We worked around the problem, but going to re-open until we have a check enabled again.

**Comment by pdehaan** [comment]
Here was my minimal code for switching to **grunt-nsp**:
```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

module.exports = function (grunt) {
  grunt.config('nsp', {
    package: grunt.file.readJSON('package.json'),
    shrinkwrap: grunt.file.readJSON('npm-shrinkwrap.json')
  });
};
```

**Comment by shane-tomlinson** [comment]
@pdehaan - so simple!

**Comment by pdehaan** [comment]
Meh. I'd argue that it should try and grab the package.json and npm-shrinkwrap.json by default (similar to how **grunt-nsp-shrinkwrap** worked) but that's just me. Actually, I may file that upstream. It's pretty lame that our Travis broke overnight due to API changes.

**Comment by philbooth** [comment]
Closing, new issue to follow.
