### ISSUE TITLE
change password functional tests intermittently fail on CircleCI

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3373]
https://circleci.com/gh/mozilla/fxa-content-server/1796

```
Suite firefox on any platform - settings->change password with verified email FAILED
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/5c146e5f-c193-4e25-8ab1-c93973229274/element/1105/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'box142', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-71-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:413:10>
  at <tests/functional/change_password.js:73:36>
  at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1312:9>
  at Object.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1019:6>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
Suite firefox on any platform - settings->change password with verified email FAILED
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/5c146e5f-c193-4e25-8ab1-c93973229274/element/1105/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'box142', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-71-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:413:10>
  at <tests/functional/change_password.js:73:36>
  at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1312:9>
  at Object.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1019:6>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
Suite firefox on any platform - settings->change password with verified email FAILED
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/5c146e5f-c193-4e25-8ab1-c93973229274/element/1105/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'box142', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-71-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:413:10>
  at <tests/functional/change_password.js:73:36>
  at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1312:9>
  at Object.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1019:6>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
Suite firefox on any platform - settings->change password with verified email FAILED
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/5c146e5f-c193-4e25-8ab1-c93973229274/element/1105/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'box142', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-71-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:413:10>
  at <tests/functional/change_password.js:73:36>
  at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1312:9>
  at Object.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1019:6>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
Suite firefox on any platform - settings->change password with verified email FAILED
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/5c146e5f-c193-4e25-8ab1-c93973229274/element/1105/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'box142', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-71-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Object.fillOutSignIn  <tests/functional/lib/helpers.js:413:10>
  at <tests/functional/change_password.js:73:36>
  at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1312:9>
  at Object.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1019:6>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>

```

I saw this yesterday multiple times as well.

Ref #3324

**Comment by jstrutz** [comment]
Just to add a data point; the timing of this seems to coincide with some trouble CircleCI was having: http://status.circleci.com/incidents/jhcmlldfgnld

**Comment by vladikoff** [comment]
This could be fixed by https://github.com/mozilla/fxa-dev/issues/213

**Comment by shane-tomlinson** [comment]
I pulled this into next, I have seen this 3x today.

**Comment by vladikoff** [comment]
fixing  #3461  might help

**Comment by vladikoff** [comment]
@vbudhram and @vladikoff to chat about this

**Comment by vbudhram** [comment]
I will continue to monitor this, it should be fixed via #3535.

**Comment by vladikoff** [comment]
:+1: we can close this though and reopen if needed

**Comment by vbudhram** [comment]
SGTM
