### ISSUE TITLE
functional tests failing beginning with 'firefox on any platform - verification_experiments - open gmail - treatment works'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3453]
I had to disable updates to sessionToken on Friday. Tests all passed with that change in stage at that time, but tests are failing on latest and stage, and I'm thinking this could be related to disabling those updates. (After this test fails, everything after that fails with `Error communicating with the remote browser. It may have died.`)

http://tests.dev.lcip.org:8111/viewLog.html?buildId=8664&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=397
```
[20:01:43][Step 1/1]  [91m× firefox on any platform - verification_experiments - open gmail - treatment works [37m (30.061s)
[20:01:43][Step 1/1]  [31mCancelError: Timeout reached on firefox on any platform - verification_experiments - open gmail - treatment works
[20:01:43][Step 1/1]  at null._onTimeout <node_modules/intern/lib/Test.js:162:20>
[20:01:43][Step 1/1]  at Timer.listOnTimeout [as ontimeout] <timers.js:121:15>
[20:01:43][Step 1/1]  at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
[20:01:43][Step 1/1]  at Command <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
[20:01:43][Step 1/1]  at <node_modules/intern/lib/Test.js:236:37>
[20:01:43][Step 1/1]  at Promise.cancel <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
[20:01:43][Step 1/1]  at null._onTimeout <node_modules/intern/lib/Test.js:164:21>
[20:01:43][Step 1/1]  at Timer.listOnTimeout [as ontimeout] <timers.js:121:15> [0m
[20:01:47][Step 1/1]  [91m× firefox on any platform - verification_experiments - open gmail - control works [37m (2.862s)
[20:01:47][Step 1/1]  [31mUnknownError: [POST http://localhost:4444/wd/hub/session/4bcd6b98-fd67-492e-8714-9b1adc19a401/url / {"url":"https://latest.dev.lcip.org/signup?forceExperiment=openGmail&forceExperimentGroup=control"}] Error communicating with the remote browser. It may have died.
[20:01:47][Step 1/1] Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
[20:01:47][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[20:01:47][Step 1/1] Driver info: driver.version: EventFiringWebDriver
[20:01:47][Step 1/1]  at runRequest <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
[20:01:47][Step 1/1]  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
[20:01:47][Step 1/1]  at new Promise <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
[20:01:47][Step 1/1]  at ProxiedSession._post <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
[20:01:47][Step 1/1]  at ProxiedSession.Session.get <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
[20:01:47][Step 1/1]  at ProxiedSession.lang.mixin.get <node_modules/intern/lib/ProxiedSession.js:90:23>
[20:01:48][Step 1/1]  at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
[20:01:48][Step 1/1]  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
[20:01:48][Step 1/1]  at Object.run [as _onImmediate] <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
[20:01:48][Step 1/1]  at processImmediate [as _immediateCallback] <timers.js:363:15>
[20:01:48][Step 1/1]  at Command.target.(anonymous function) [as get] <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
[20:01:48][Step 1/1]  at Test.registerSuite.control works [as test] <tests/functional/verification_experiments.js:70:10>
[20:01:48][Step 1/1]  at start.then.finally.self.timeElapsed <node_modules/intern/lib/Test.js:211:24>
[20:01:48][Step 1/1]  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
[20:01:48][Step 1/1]  at runCallbacks <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
[20:01:48][Step 1/1]  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
[20:01:48][Step 1/1]  at Object.run [as _onImmediate] <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
[20:01:48][Step 1/1]  at processImmediate [as _immediateCallback] <timers.js:363:15> [0m
[20:01:48][Step 1/1]  [41mSuite firefox on any platform - verification_experiments - open gmail FAILED
[20:01:48][Step 1/1] UnknownError: [POST http://localhost:4444/wd/hub/session/4bcd6b98-fd67-492e-8714-9b1adc19a401/frame / {"id":null}] Error communicating with the remote browser. It may have died.
[20:01:48][Step 1/1] Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
[20:01:48][Step 1/1] System info: host: 'ip-172-31-11-113', ip: '172.31.11.113', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-51-generic', java.version: '1.7.0_80'
[20:01:48][Step 1/1] Driver info: driver.version: RemoteWebDriver
[20:01:48][Step 1/1]  at runRequest <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
[20:01:48][Step 1/1]  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
[20:01:48][Step 1/1]  at new Promise <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
[20:01:48][Step 1/1]  at ProxiedSession._post <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
```

**Comment by shane-tomlinson** [comment]
The problem is with [this line in fxa-content-experiments](https://github.com/mozilla/fxa-content-experiments/blob/f3492f244a449ed2525b307602858e12d283f995/verification/open-gmail.js#L7)

@vladikoff - this is the 2nd time an `endDate` has screwed us. Let's remove all of those unless we know for certain the experiment is going to end.
