### ISSUE TITLE
"signin with new permission available b/c of new account information" - TeamCity tests failing

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3541]
Ref: http://tests.dev.lcip.org:8111/viewLog.html?buildId=9255&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog
```
[21:10:49][Step 1/1]  [31mCancelError: Timeout reached on firefox on any platform - oauth permissions for untrusted reliers - signin with new permission available b/c of new account information
[21:10:49][Step 1/1]   at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
[21:10:49][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
[21:10:49][Step 1/1]   at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
[21:10:49][Step 1/1]   at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
[21:10:49][Step 1/1]   at <node_modules/intern/lib/Test.js:236:37>
[21:10:49][Step 1/1]   at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
[21:10:49][Step 1/1]   at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
[21:10:49][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15> [0m
[21:11:32][Step 1/1]  [91m× firefox on any platform - oauth permissions for untrusted reliers - signin with additional requested permission [37m (30.037s)
[21:11:32][Step 1/1]  [31mCancelError: Timeout reached on firefox on any platform - oauth permissions for untrusted reliers - signin with additional requested permission
[21:11:32][Step 1/1]   at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
[21:11:32][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
[21:11:32][Step 1/1]   at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
[21:11:32][Step 1/1]   at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
[21:11:32][Step 1/1]   at <node_modules/intern/lib/Test.js:236:37>
[21:11:32][Step 1/1]   at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
[21:11:32][Step 1/1]   at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
[21:11:32][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15> [0m
[21:12:16][Step 1/1]  [91m× firefox on any platform - oauth permissions for untrusted reliers - signin after de-selecting a requested permission [37m (30.048s)
[21:12:16][Step 1/1]  [31mCancelError: Timeout reached on firefox on any platform - oauth permissions for untrusted reliers - signin after de-selecting a requested permission
[21:12:16][Step 1/1]   at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
[21:12:16][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15>
[21:12:16][Step 1/1]   at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
[21:12:16][Step 1/1]   at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
[21:12:16][Step 1/1]   at <node_modules/intern/lib/Test.js:236:37>
[21:12:16][Step 1/1]   at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
[21:12:16][Step 1/1]   at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
[21:12:16][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:121:15> [0m
```

**Comment by vladikoff** [comment]
@shane-tomlinson in this test:

```
'signin with new permission available b/c of new account information': function () {
      var self = this;

      return openFxaFromUntrustedRp(self, 'signin')
        .then(createUser(email, PASSWORD, { preVerified: true }))

        .then(fillOutSignIn(self, email, PASSWORD))

        .then(testElementExists('#fxa-permissions-header'))

        // display name is not available because user has not set their name
        .then(noSuchElement(self, 'input[name="profile:display_name"]'))

        .then(click('#accept'))

        .then(testElementExists('#loggedin'))
        .then(testUrlEquals(UNTRUSTED_OAUTH_APP))

        .then(click('#logout'))

        .then(openSettingsInNewTab(self, 'settings', 'display_name'))
        .switchToWindow('settings')

        .then(type('#display-name input[type=text]', 'test user'))
        .then(click('#display-name button[type=submit]'))

        .then(visibleByQSA('.settings-success'))

        .closeCurrentWindow()
        .switchToWindow('')

        .then(click('.signin'))

        .then(type('input[type=password', PASSWORD))
        .then(click('button[type=submit]'))

        // display name is now available
        .then(testElementExists('input[name="profile:display_name"]'))

        .then(click('#accept'))
        .then(testElementExists('#loggedin'));
    },
```

Instead of showing the display name + permission:
```

        // display name is now available
        .then(testElementExists('input[name="profile:display_name"]'))
```

we just get a log in to 123done. Do we need to clear the storage between the login attempts?

**Comment by vladikoff** [comment]
@shane-tomlinson I think you will know the issue right away, to get this to fail just run 

```
./node_modules/.bin/intern-runner config=tests/intern_functional_full fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ fxaIframeOauthApp=https://123done-latest.dev.lcip.org/iframe fxaEmailRoot=http://restmail.net fxaProduction=true grep="b/c"
```

**Comment by shane-tomlinson** [comment]
@vladikoff - that 321done is not requesting the `profile:display_name` scope:

> https://latest.dev.lcip.org/oauth/signin?client_id=325b4083e32fe8e7&state=45e2530442b5c00c601a3029f84b227b552fa435c15ecfbd317bcea617660ffe&scope=profile%3Aemail%20profile%3Auid&redirect_uri=https%3A%2F%2F321done-latest.dev.lcip.org%2Fapi%2Foauth


I suspect [this 123done PR](https://github.com/mozilla/123done/pull/149) is not yet applied there.
