### ISSUE TITLE
oauth query parameter validation - invalid access_type fails on latest

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3572]
### STR

Start up selenium, run

```
npm run test-latest grep="parameter validation"
```

## Output

```
× firefox on any platform - oauth query parameter validation - invalid access_type (30.004s)
CancelError: Timeout reached on firefox on any platform - oauth query parameter validation - invalid access_type
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout  <timers.js:92:15>
✓ firefox on any platform - oauth query parameter validation - valid access_type (offline) (0.62s)
✓ firefox on any platform - oauth query parameter validation - valid access_type (online) (0.68s)
× firefox on any platform - oauth query parameter validation - missing client_id (30.003s)
CancelError: Timeout reached on firefox on any platform - oauth query parameter validation - missing client_id
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout  <timers.js:92:15>

```

![image](https://cloud.githubusercontent.com/assets/128755/13613980/57b55580-e53c-11e5-9709-5c3e026fc2c8.png)

**Comment by vbudhram** [comment]
Looks like they are failing in dev environment because it is checking for an error label exists. It should look like this.
![screen shot 2016-03-08 at 4 23 02 pm](https://cloud.githubusercontent.com/assets/1295288/13616943/21e6b99a-e54a-11e5-8e69-b0c6352abc90.png)

Is it possible that the 400 page got overridden with an older version?

**Comment by vbudhram** [comment]
Did a little more digging and found that https://latest.dev.lcip.org/400.html, has `integrity` and `crossorigin` attributes on the link tag and don't have these when testing locally. I thought it could be that the files needed to be invalidated if they were behind the CDN, but @vladikoff said the CDN is not enabled in the dev environment. @shane-tomlinson, what do you think might cause this?

**Comment by shane-tomlinson** [comment]
This is due to https://github.com/mozilla/fxa-content-server/issues/2070
