### ISSUE TITLE
Failing functional test: "signup - signup with existing account, coppa is valid, credentials are wrong"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3704]
> ✓ firefox on any platform - signup - signup with existing account, coppa is valid, credentials are correct (0.969s)
× firefox on any platform - signup - signup with existing account, coppa is valid, credentials are wrong (29.84s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/46328520-05d5-447f-962c-b3fbc66fdbe8/element / {"using":"css selector","value":"#fxa-signin-header"}] Unable to locate element: {"method":"css selector","selector":"#fxa-signin-header"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'Shanes-Retina-MBP.local', ip: '10.246.29.79', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.7.0_40'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1125:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at Test.registerSuite.signup with existing account, coppa is valid, credentials are wrong [as test]  <tests/functional/sign_up.js:303:10>
  at <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>

STR: 

1. Run `npm run test-functional grep="signup with existing account, coppa is valid"`

**Comment by shane-tomlinson** [comment]
Only manifests with Selenium 2.53.0, 2.47.1 works fine.

**Comment by shane-tomlinson** [comment]
The problem appears to be the error message is not fully displayed before the signin link is clicked.

**Comment by shane-tomlinson** [comment]
Blocks #3703

**Comment by shane-tomlinson** [comment]
Also affects "delete_account - locked account, verify different browser - from original tab's P.O.V."

**Comment by shane-tomlinson** [comment]
Also affects "settings->change password with verified email - locked account, verify different browser - from new browser's P.O.V."
