### ISSUE TITLE
test crash (browser may have died) running tests

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3730]
I keep hitting this on my VM on this test (Fx46, Ubuntu 14.04.4 LTS). Fails the first test then everything fails as the browser either crashed or quit.

```
× firefox on any platform - delete_account - locked account, verify same browser with
         original tab closed (30.032s)
CancelError: Timeout reached on firefox on any platform - delete_account - locked account, 
         verify same browser with original tab closed
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
Waiting for email at: http://restmail.net/mail/signin0.12243667338043451
Waiting for email at: http://restmail.net/mail/signin0.12243667338043451
Waiting for email at: http://restmail.net/mail/signin0.12243667338043451
Suite firefox on any platform - delete_account FAILED
NoSuchWindow: [POST http://localhost:4444/wd/hub/session/9eda88a3-817c-4b7c-bd1d-3bc3201fe50a/timeouts / {"type":"implicit","ms":28000}] Window not found. 
     The browser window may have been closed.
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.setTimeout  <node_modules/intern/node_modules/leadfoot/Session.js:492:22>
  at ProxiedSession.<anonymous>  <node_modules/intern/node_modules/leadfoot/Session.js:2286:16>
  at ProxiedSession.setFindTimeout  <node_modules/intern/node_modules/dojo/lang.ts:85:12>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at Command.target.(anonymous function) [as setFindTimeout]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:81:22>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at clearContentServerState  <tests/functional/lib/helpers.js:76:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:52:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Object.clearBrowserState  <tests/functional/lib/helpers.js:50:8>
  at Suite.registerSuite.afterEach  <tests/functional/delete_account.js:72:32>
  at Suite.target.(anonymous function).dispatcher [as afterEach]  <node_modules/intern/browser_modules/dojo/aspect.ts:102:35>
  at Promise.catch.suite.async  <node_modules/intern/lib/Suite.js:227:51>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at runLifecycleMethod  <node_modules/intern/lib/Suite.js:209:12>
  at runWithCatch  <node_modules/intern/lib/Suite.js:339:15>
  at next  <node_modules/intern/lib/Suite.js:342:17>
  at <node_modules/intern/lib/Suite.js:345:6>
Waiting for email at: http://restmail.net/mail/signin0.12243667338043451
Suite firefox on any platform - delete_account FAILED
UnknownError: [POST http://localhost:4444/wd/hub/session/9eda88a3-817c-4b7c-bd1d-3bc3201fe50a/frame / {"id":null}] 
Error communicating with the remote browser. It may have died.
```

**Comment by jrgm** [comment]
So `var payload = args[1]` must be falsy: `undefined`, `0`, or `''`.

**Comment by jrgm** [comment]
> So var payload = args[1] must be falsy: undefined, 0, or ''.

Ignore that. Posted into the wrong bug.

**Comment by vladikoff** [comment]
we shall keep an eye on it!
