### ISSUE TITLE
`Firstrun v1 sign_in - unverified` Flaky functional test on circle ci

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3790]
```
× firefox on any platform - Firstrun v1 sign_in - unverified (29.381s)
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/9c5754df-25f4-4721-8a86-d1903afcad2a/element/554/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'box51.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-86-generic', java.version: '1.8.0_40'
Driver info: driver.version: unknown
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1138:12>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.fillOutSignIn  <tests/functional/lib/helpers.js:539:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1120:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.<anonymous>  <tests/functional/fx_firstrun_v1_sign_in.js:39:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1120:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.unverified [as test]  <tests/functional/fx_firstrun_v1_sign_in.js:65:10>
  at <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
```

**Comment by vladikoff** [comment]
This will be fixed via https://github.com/mozilla/fxa-content-server/pull/3725

**Comment by vladikoff** [comment]
This happens because we arrive at the suggested account screen: 


![image](https://cloud.githubusercontent.com/assets/128755/15659142/06f6d134-2694-11e6-9970-b8c355e46c9b.png)

**Comment by vladikoff** [comment]
fixed in https://github.com/mozilla/fxa-content-server/commit/9d267ab2053377ee0a0bb7aceba05d447f2bd643
