### ISSUE TITLE
Tests: some sign_in functional tests missing sign in screen

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3892]
If you run

```
npm run test-functional grep="mail"
```

the sign in tests will fail with:

```
➜  fxa-content-server git:(master) ✗ npm run test-functional grep="mail"

> fxa-content-server@0.64.0 test-functional /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional "grep=mail"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (7093c992-e81b-4d72-a2ee-7ee53a2168bc)
✓ firefox on any platform - sign_in - with an invalid email (0.891s)
~ firefox on any platform - sign_in - sign in unverified (grep)
~ firefox on any platform - sign_in - redirect to requested page after sign in verified with correct password (grep)
~ firefox on any platform - sign_in - sign in verified with correct password (grep)
~ firefox on any platform - sign_in - sign in verified with incorrect password, click `forgot password?` (grep)
~ firefox on any platform - sign_in - sign in with an unknown account allows the user to sign up (grep)
× firefox on any platform - sign_in - sign in with email with leading space strips space (30.006s)
CancelError: Timeout reached on firefox on any platform - sign_in - sign in with email with leading space strips space
  at null.<anonymous>  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:92:15>

```

Ref: https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/sign_in.js#L151

**Comment by vladikoff** [comment]
There is no `beforeEach` on these tests, so they don't go back to the sign in page

**Comment by vladikoff** [comment]
Hasn't been an issue for months, 🗡
