### ISSUE TITLE
Failing functional test on master: "Sync v1 sign_in - verified, verify same browser"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4143]
```
× firefox on any platform - Firefox Desktop Sync v1 sign_in - verified, verify same browser (30.01s)
CancelError: Timeout reached on firefox on any platform - Firefox Desktop Sync v1 sign_in - verified, verify same browser
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout  <timers.js:92:15>
```

**Comment by shane-tomlinson** [comment]
Selenium console shows an error:

```
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"css selector","selector":"#fxa-confirm-signin-header"}
```

**Comment by shane-tomlinson** [comment]
Closing, this is because I had a development version of the auth server running.
