### ISSUE TITLE
#message-profile-change cannot be found by functional tests

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4144]
```
firefox on any platform - settings/avatar (3)
 firefox on any platform - settings/avatar - attempt to use webcam for avatar 	
 firefox on any platform - settings/avatar - upload a profile image 	
 firefox on any platform - settings/avatar - visit gravatar with gravatar set 	
```
https://tc-test.dev.lcip.org/viewLog.html?buildId=10803&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

```
× firefox on any platform - settings/avatar - attempt to use webcam for avatar (29.835s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/9cd9c73d-e9f5-4e7b-8248-25e9e997fd43/element / {"using":"css selector","value":"#message-profile-change"}] Unable to locate element: {"method":"css selector","selector":"#message-profile-change"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'Vlads-MBP', ip: '192.168.1.199', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_92'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1125:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at Command.<anonymous>  <tests/functional/avatar.js:36:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1245:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.attempt to use webcam for avatar [as test]  <tests/functional/avatar.js:195:10>
  at <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
@vladikoff - it's because of #4142, looks like an abstraction was broken by looking for the element directly instead of using the helpers.
