### ISSUE TITLE
Tests: flaky tests on Circle FxiOS v1 sign_in

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4330]
```
× firefox on any platform - FxiOS v1 sign_in - verified, verify same browser (30.024s)
CancelError: Timeout reached on firefox on any platform - FxiOS v1 sign_in - verified, verify same browser
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout  <timers.js:92:15>
× firefox on any platform - FxiOS v1 sign_in - verified, verify different browser - from original tab's P.O.V. (30.022s)
CancelError: Timeout reached on firefox on any platform - FxiOS v1 sign_in - verified, verify different browser - from original tab's P.O.V.
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout  <timers.js:92:15>
```

![](http://v14d.com/i/5810ace3f36ee.png)

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/4333
