### ISSUE TITLE
failing functional test: "sign_in cached - sign in first in sync context, on second attempt credentials will be cached"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4380]
When run in isolation locally, this test fails 100% of the time, using master of all servers:

```
× firefox on any platform - sign_in cached - sign in first in sync context, on second attempt credentials will be cached (30.01s)
CancelError: Timeout reached on firefox on any platform - sign_in cached - sign in first in sync context, on second attempt credentials will be cached
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout  <timers.js:92:15>
```

**Comment by shane-tomlinson** [comment]
Doh, I had a local uncommited modification in the auth server. Closing.
