### ISSUE TITLE
Failing circle test - "firefox on any platform - Firefox Desktop Sync v1 reset_password - reset password, verify different browser - from original tab's P.O.V."

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4399]
Against current master, every time:

```
AssertionError: expected true to be false
  at Assertion.<anonymous>  <node_modules/intern/browser_modules/chai/chai.js:589:10>
  at Assertion.addProperty  <node_modules/intern/browser_modules/chai/chai.js:4240:29>
  at Function.assert.isFalse  <node_modules/intern/browser_modules/chai/chai.js:2521:31>
  at Command.<anonymous>  <tests/functional/lib/fx-desktop.js:80:20>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.testIsBrowserNotifiedOfLogin  <tests/functional/lib/fx-desktop.js:71:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1310:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.reset password, verify different browser - from original tab's P.O.V. [as test]  <tests/functional/sync_reset_password.js:134:10>
  at <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

**Comment by shane-tomlinson** [comment]
I believe this is caused by https://github.com/mozilla/fxa-auth-server/pull/1525.

**Comment by shane-tomlinson** [comment]
Sometimes this test fails with an internal server error (using new tests):

```
× firefox on any platform - settings clients - device and apps panel works with query param, same device (10.071s)
Error: An internal server error occurred
undefined
    at Command.then (/Users/stomlinson/development/fxa-content-server/node_modules/intern/node_modules/leadfoot/Command.js:542:10)
    at Test.registerSuite.device and apps panel works with query param, same device [as test] (/Users/stomlinson/development/fxa-content-server/tests/functional/settings_clients.js:104:10)
    at /Users/stomlinson/development/fxa-content-server/node_modules/intern/lib/Test.js:181:24
    at /Users/stomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:156:41
    at runCallbacks (/Users/stomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:19:22)
    at /Users/stomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:103:21
    at run (/Users/stomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:51:33)
    at /Users/stomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/nextTick.js:35:17
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```
