### ISSUE TITLE
String extraction cannot extract "const"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4406]
```
Running "jsxextract" task
fxa-content-server.CRITICAL: uncaughtException SyntaxError: Unexpected token (7:6)
  at raise (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/jsxgettext-recursive/node_modules/jsxgettext/node_modules/acorn/acorn.js:236:15)
  at unexpected (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/jsxgettext-recursive/node_modules/jsxgettext/node_modules/acorn/acorn.js:1094:5)
  at semicolon (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/jsxgettext-recursive/node_modules/jsxgettext/node_modules/acorn/acorn.js:1080:47)
  at parseStatement (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/jsxgettext-recursive/node_modules/jsxgettext/node_modules/acorn/acorn.js:1350:9)
  at parseTopLevel (/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/jsxgettext-recursive/node_modules/jsxgettext/node_modules/acorn/acorn.js:1124:18)
  at Object.exports.parse (/Users/vladikoff/mozilla/fxa-local-dev/fxa-
```

**Comment by vladikoff** [comment]
Need to update jsxgettext

**Comment by vladikoff** [comment]
Update all the things with `'joinExisting': true,` otherwise mustache files overwrite the js strings
