### ISSUE TITLE
Failing OAuth functional test - "Sign in with OAuth after Sync - sign in to OAuth with Sync creds"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4421]
I saw this while testing https://github.com/mozilla/fxa-content-server/pull/4419

```
× firefox on any platform - Sign in with OAuth after Sync - sign in to OAuth with Sync creds (2.42s)
AssertionError: expected true to be false
  at Assertion.<anonymous>  <node_modules/intern/browser_modules/chai/chai.js:589:10>
  at Assertion.addProperty  <node_modules/intern/browser_modules/chai/chai.js:4240:29>
  at Function.assert.isFalse  <node_modules/intern/browser_modules/chai/chai.js:2521:31>
  at Command.<anonymous>  <tests/functional/lib/fx-desktop.js:80:20>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.testIsBrowserNotifiedOfLogin  <tests/functional/lib/fx-desktop.js:71:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1303:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.sign in to OAuth with Sync creds [as test]  <tests/functional/oauth_sync_sign_in.js:66:10>
  at <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

**Comment by shane-tomlinson** [comment]
Ref #4420

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/fxa-content-server/pull/4428

**Comment by shane-tomlinson** [comment]
Fixed, closing!
