### ISSUE TITLE
Node 6 travis builds are failing, failing to connect to auth and db

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4507]
Ref https://travis-ci.org/mozilla/fxa-content-server/jobs/184018751

```
Suite firefox on any platform - reset_password FAILED
Error: Error: connect ECONNREFUSED 127.0.0.1:9000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
undefined
```

**Comment by vladikoff** [comment]
Hm tested on Ubuntu locally, the only problem I had was that install required C++11
We currently use g++ 4.8 package, but there is 5.2. Not clear if that is the issue or not...

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/4958
