### ISSUE TITLE
Fix up GA server timing tests

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4675]
Ref: https://tc-test.dev.lcip.org/viewLog.html?buildId=8885&tab=buildResultsDiv&buildTypeId=fxa_StageServerTests
```
AssertionError: expected 4001 to equal 4000
  at Function.assert.equal  <node_modules/intern/browser_modules/chai/chai.js:2277:10>
  at Test.suite.describes _calculateQueueTime [as test]  <tests/server/metrics-ga.js:96:12>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
```

**Comment by vladikoff** [comment]
from mtg: have not seen this in a while
