### ISSUE TITLE
uncaughtExceptions in lib/flow-event

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4821]
In releasing the train, I had these, so had to roll back to previous. Not terribly common, but no choice.

TypeError: Cannot read property 'domainLookupStart' of undefined
    at /data/fxa-content-server/server/lib/flow-event.js:133:38
    at Array.reduce (native)
    at /data/fxa-content-server/server/lib/flow-event.js:132:33
    at Array.forEach (native)
    at module.exports.events.map.flowEvents.forEach.PERFORMANCE_TIMINGS.forEach.item (/data/fxa-content-server/server/lib/flow-event.js:131:25)
    at /data/fxa-content-server/server/lib/routes/post-metrics.js:155:9
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickDomainCallback (node.js:459:13)

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-content-server/pull/4776

cc @philbooth , any quick fixes for this?
