### ISSUE TITLE
flaky test: settings/avatar - visit gravatar with gravatar set

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4843]
This test needs to refactored or checked.
Stack against `latest` via TeamCity:

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/907def0e-a972-477b-9b6c-c46db0e659a6/element / {"using":"css selector","value":".success[data-shown]"}] Unable to locate element: .success[data-shown]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: '355b98b72e11', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '3.14.48-33.39.amzn1.x86_64', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, firefox_binary=/home/teamcity/firefox-channels/latest/en-US/firefox/firefox-bin, acceptSslCerts=false, processId=908, browserVersion=50.1.0, platformVersion=3.14.48-33.39.amzn1.x86_64, name=tests/intern_functional_full, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux, firefox_profile=UEsDBBQACAgIAJEAdkoAAAAAAAAAA...}]
Session ID: 49e4d0a1-1d47-4107-935d-4cebaef99d06
*** Element info: {Using=css selector, value=.success[data-shown]}
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1304:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:29:16>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:165:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1264:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.visit gravatar with gravatar set [as test]  <tests/functional/avatar.js:117:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>

**Comment by vladikoff** [comment]
should be fixed.
