### ISSUE TITLE
Failing functional test locally - firefox on any platform - password change while at confirm_reset_password screen - original page transitions after completion

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4915]
> Error: Email account hard bounced
undefined
    at Command.then (/Users/shanetomlinson/development/fxa-content-server/node_modules/intern/node_modules/leadfoot/Command.js:542:10)
    at Test.registerSuite.original page transitions after completion [as test] (/Users/shanetomlinson/development/fxa-content-server/tests/functional/reset_password.js:475:10)
    at /Users/shanetomlinson/development/fxa-content-server/node_modules/intern/lib/Test.js:191:24
    at /Users/shanetomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:156:41
    at runCallbacks (/Users/shanetomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:19:22)
    at /Users/shanetomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:103:21
    at run (/Users/shanetomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/Promise.js:51:33)
    at /Users/shanetomlinson/development/fxa-content-server/node_modules/intern/browser_modules/dojo/nextTick.js:35:17
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

**Comment by shane-tomlinson** [comment]
This is because I modified my fxa-js-client. Closing.
