### ISSUE TITLE
flaky functional test on circle - settings clients - device and apps panel works with query param, same device 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5071]
I've seen this several times today: https://circleci.com/gh/mozilla/fxa-content-server/6961#tests/containers/1

> × firefox on any platform - settings clients - device and apps panel works with query param, same device (3.232s)
StaleElementReference: [GET http://localhost:4444/wd/hub/session/7547b96e-2dff-4312-a540-9952964e0105/element/649/text] The element reference of <div class="client-name"> stale: either the element is no longer attached to the DOM or the page has been refreshed
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-117-generic', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.ub55h506yT02, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=3.13.0-117-generic, moz:processID=22306.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: afffbddf-3157-4a61-a2b9-b15eaacd65c4
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._get  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at Element._get  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.getVisibleText  <node_modules/intern/node_modules/leadfoot/Element.js:233:21>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as getVisibleText]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1459:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:489:9>
  at process._tickCallback  <node.js:418:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.device and apps panel works with query param, same device [as test]  <tests/functional/settings_clients.js:127:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:489:9>
  at process._tickCallback  <node.js:418:13>

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa-content-server/issues/4570
