### ISSUE TITLE
Test failure on master/circle - settings clients - sessions are listed in clients view

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5230]
https://circleci.com/gh/mozilla/fxa-content-server/7471?utm_campaign=build-failed&utm_medium=email&utm_source=notification

> × firefox on any platform - settings clients - sessions are listed in clients view (5.063s)
AssertionError: expected 'Web Session,' to equal 'Web Session, node-XMLHttpRequest'
  at Function.assert.equal  <node_modules/intern/browser_modules/chai/chai.js:2277:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1582:16>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1581:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Test.sessions are listed in clients view [as test]  <tests/functional/settings_clients.js:80:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>

A quick screen cap of what shows in the content server:

<img width="509" alt="screen shot 2017-07-12 at 11 18 45" src="https://user-images.githubusercontent.com/848085/28113566-f6783224-66f4-11e7-971c-7dc0adc97828.png">

**Comment by shane-tomlinson** [comment]
The screen cap shows when no userAgent is returned for the item, an extra comma appears.
