### ISSUE TITLE
change email tests failing on teamcity against latest

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5304]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=14059&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog

> [settings change email] SUITE ERROR
NoSuchElement: [POST http://localhost:4444/wd/hub/session/49a9e8c9-152a-4760-b5b5-80aaea54c84a/element / {"using":"css selector","value":".email-address .set-primary"}] Unable to locate element: .email-address .set-primary
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'c7a487beed90', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/home/teamcity/agent/temp/buildTmp/rust_mozprofile.J2Zs6Sz7FEui, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.2, platformVersion=4.4.41-36.55.amzn1.x86_64, moz:processID=14462.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: 6c725872-2ecf-4d9b-a380-3708354cc1b4
*** Element info: {Using=css selector, value=.email-address .set-primary}
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1304:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:29:16>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:150:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Suite.registerSuite.beforeEach  <tests/functional/settings_change_email.js:73:10>
  at Suite.target.(anonymous function).dispatcher [as beforeEach]  <node_modules/intern/browser_modules/dojo/aspect.ts:102:35>
  at Promise.catch.suite.async  <node_modules/intern/lib/Suite.js:237:51>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at runLifecycleMethod  <node_modules/intern/lib/Suite.js:219:12>
  at runWithCatch  <node_modules/intern/lib/Suite.js:349:15>
  at next  <node_modules/intern/lib/Suite.js:352:17>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>

> [18:46:33]
[settings change email] SUITE ERROR
NoSuchElement: [POST http://localhost:4444/wd/hub/session/49a9e8c9-152a-4760-b5b5-80aaea54c84a/element / {"using":"css selector","value":".email-address .set-primary"}] Unable to locate element: .email-address .set-primary
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'c7a487beed90', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/home/teamcity/agent/temp/buildTmp/rust_mozprofile.J2Zs6Sz7FEui, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.2, platformVersion=4.4.41-36.55.amzn1.x86_64, moz:processID=14462.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: 6c725872-2ecf-4d9b-a380-3708354cc1b4
*** Element info: {Using=css selector, value=.email-address .set-primary}
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1304:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:29:16>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:150:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Suite.registerSuite.beforeEach  <tests/functional/settings_change_email.js:73:10>
  at Suite.target.(anonymous function).dispatcher [as beforeEach]  <node_modules/intern/browser_modules/dojo/aspect.ts:102:35>
  at Promise.catch.suite.async  <node_modules/intern/lib/Suite.js:237:51>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at runLifecycleMethod  <node_modules/intern/lib/Suite.js:219:12>
  at runWithCatch  <node_modules/intern/lib/Suite.js:349:15>
  at next  <node_modules/intern/lib/Suite.js:352:17>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>

> [18:47:20]
[settings change email] SUITE ERROR
NoSuchElement: [POST http://localhost:4444/wd/hub/session/49a9e8c9-152a-4760-b5b5-80aaea54c84a/element / {"using":"css selector","value":".email-address .set-primary"}] Unable to locate element: .email-address .set-primary
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'c7a487beed90', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/home/teamcity/agent/temp/buildTmp/rust_mozprofile.J2Zs6Sz7FEui, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.2, platformVersion=4.4.41-36.55.amzn1.x86_64, moz:processID=14462.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: 6c725872-2ecf-4d9b-a380-3708354cc1b4
*** Element info: {Using=css selector, value=.email-address .set-primary}
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1304:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:29:16>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:150:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Suite.registerSuite.beforeEach  <tests/functional/settings_change_email.js:73:10>
  at Suite.target.(anonymous function).dispatcher [as beforeEach]  <node_modules/intern/browser_modules/dojo/aspect.ts:102:35>
  at Promise.catch.suite.async  <node_modules/intern/lib/Suite.js:237:51>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at runLifecycleMethod  <node_modules/intern/lib/Suite.js:219:12>
  at runWithCatch  <node_modules/intern/lib/Suite.js:349:15>
  at next  <node_modules/intern/lib/Suite.js:352:17>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>

**Comment by shane-tomlinson** [comment]
This is reproducible locally and against latest using Firefox 53

`npm run test-latest grep="settings change email"`
or 
`npm run test-functional grep="settings change email"`
