### ISSUE TITLE
Fx 54 failing functional test - "firefox on any platform - oauth permissions for untrusted reliers - signin after de-selecting a requested permission"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5305]
STR

1. `npm run test-latest grep="oauth permissions for untrusted reliers"`
2. Kaboom.

> × firefox on any platform - oauth permissions for untrusted reliers - signin after de-selecting a requested permission (11.263s)
Error: [POST http://localhost:4444/wd/hub/session/fc10345b-823f-4c64-a39d-5bed483896e5/element/160/click / {}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'stomlinson-30887', ip: '10.239.30.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/cq/drrh74v57_x_x6ksf_7pk2x80000gn/T/rust_mozprofile.gF2AJbnJwiuO, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=16.6.0, moz:processID=84506.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 708385db-dd15-7747-8b68-562038890205
  at runRequest  <node_modules/leadfoot/Session.js:92:40>
  at <node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/leadfoot/Session.js:67:10>
  at Element._post  <node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/leadfoot/Element.js:191:15>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:680:19>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as click]  <node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:154:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Test.signin after de-selecting a requested permission [as test]  <tests/functional/oauth_permissions.js:300:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>

**Comment by shane-tomlinson** [comment]
The test is looking for this selector:

`input[name="profile:display_name"]`

**Comment by shane-tomlinson** [comment]
Note, this is only a problem with Fx 54, Fx 53 works fine.

**Comment by shane-tomlinson** [comment]
Also fails locally.
