### ISSUE TITLE
uncaughtException TypeError: agent.ua.toVersionString is not a function thrown in content server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5384]
> 4|content- | fxa-content-server.CRITICAL: uncaughtException TypeError: agent.ua.toVersionString is not a function
4|content- |     at getGenericTags (/Users/shanetomlinson/development/fxa-content-server/server/lib/statsd-collector.js:64:42)
4|content- |     at Object.write (/Users/shanetomlinson/development/fxa-content-server/server/lib/statsd-collector.js:236:20)
4|content- |     at process.nextTick (/Users/shanetomlinson/development/fxa-content-server/server/lib/routes/post-metrics.js:163:18)
4|content- |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
4|content- |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by shane-tomlinson** [comment]
This seems to have been caused by a bad npm install on my part. After blowing away node_modules and re-installing, no problems. Closing.
