### ISSUE TITLE
consistent test timeouts on travis with trains 94, 95, 96

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5458]
See https://travis-ci.org/mozilla/fxa-content-server/builds/273369025

> × firefox on any platform - sign_in - sign in with a second sign-in tab open (45.013s)
> CancelError: Timeout reached on firefox on any platform - sign_in - sign in with a second sign-in tab open
>  at ontimeout  <timers.js:386:11>
>  at tryOnTimeout  <timers.js:250:5>
>  at Timer.listOnTimeout  <timers.js:214:5>
>  at ontimeout  <timers.js:386:11>
>  at tryOnTimeout  <timers.js:250:5>
>  at Timer.listOnTimeout  <timers.js:214:5>

**Comment by shane-tomlinson** [comment]
Fixed by https://github.com/mozilla/fxa-content-server/pull/5468, closing.
