### ISSUE TITLE
failing functional test - Firefox Desktop Sync v1 reset_password - reset password, verify same browser

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5528]
STR

1. Run `npm run test-functional grep="Firefox Desktop Sync v1 reset_password - reset password, verify same browser"`

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/57f68a6e-de8d-4b74-8b51-b62db6e6b5a7/element / {"using":"css selector","value":"#message-login"}] Unable to locate element: #message-login
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'stomlinson-30887', ip: '192.168.0.22', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/cq/drrh74v57_x_x6ksf_7pk2x80000gn/T/rust_mozprofile.OTyKhJM5U0Qg, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=16.7.0, moz:processID=21622.0, browserName=firefox, javascriptEnabled=true, platformName=darwin}]
Session ID: 1e3d17db-1641-aa40-ab25-e86d4fa2274a
*** Element info: {Using=css selector, value=#message-login}
  at Command.<anonymous>  <tests/functional/lib/fx-desktop.js:77:10>
  at Test.reset password, verify same browser [as test]  <tests/functional/sync_reset_password.js:71:10>

Fails because `customizeSync` is not set in the Account.

**Comment by shane-tomlinson** [comment]
Also failing on teamcity: https://tc-test.dev.lcip.org/viewLog.html?buildTypeId=FxaLatest_FunctionalTests&buildId=26486

**Comment by shane-tomlinson** [comment]
This is also a problem against stage, opening a PR against train-96.
