### ISSUE TITLE
[node8] failure running travis with htmllint

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5668]
See https://travis-ci.org/mozilla/fxa-content-server/jobs/295573686#L4167-L4185

```
$ grunt htmllint:dist
Running "htmllint:dist" (htmllint) task
(node:9354) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

fxa-content-server.CRITICAL: uncaughtException TypeError: Array.prototype.slice called on null or undefined
  at slice (<anonymous>:null:null)
  at Function.Promise.all (/home/travis/build/mozilla/fxa-content-server/node_modules/promise/lib/es6-extensions.js:62:36)
  at Linter.lint (/home/travis/build/mozilla/fxa-content-server/node_modules/htmllint/lib/linter.js:58:20)
  at Linter.lint (/home/travis/build/mozilla/fxa-content-server/node_modules/promise/lib/node-extensions.js:38:17)
  at htmllint (/home/travis/build/mozilla/fxa-content-server/node_modules/htmllint/lib/index.js:11:24)
  at /home/travis/build/mozilla/fxa-content-server/node_modules/grunt-htmllint/tasks/htmllint.js:60:24
  at /home/travis/build/mozilla/fxa-content-server/node_modules/promise/lib/es6-extensions.js:18:19
  at flush (/home/travis/build/mozilla/fxa-content-server/node_modules/asap/asap.js:27:13)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at Function.Module.runMain (module.js:678:11)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3

Fatal error: Array.prototype.slice called on null or undefined
```

**Comment by vladikoff** [comment]
Oh dear!

**Comment by vladikoff** [comment]
Works fine here locally with v8.9.0 on OS X, so could be something else:

```
➜  fxa-content-server git:(master) grunt htmllint:dist
Loading "sass.js" tasks...ERROR
>> Error: Missing binding /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-57/binding.node
>> Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x
>> 
>> Found bindings for the following environments:
>>   - OS X 64-bit with Node.js 6.x
>> 
>> This usually happens because your environment has changed since running `npm install`.
>> Run `npm rebuild node-sass --force` to build the binding for your current environment.

Running "htmllint:dist" (htmllint) task
(node:33485) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
>> encountered 0 errors in total
>> 0 file(s) had lint error out of 469 file(s). (skipped 0 files)

Done.


Execution Time (2017-11-01 10:22:33 UTC-4)
loading tasks   1.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 72%
htmllint:dist  689ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 28%
Total 2.5s

➜  fxa-content-server git:(master) node --version
v8.9.0
```

**Comment by jrgm** [comment]
I've had it fail locally for me.

**Comment by vladikoff** [comment]
> I've had it fail locally for me.

From mtg: @jrgm says this happens locally on Mac OS X

**Comment by vladikoff** [comment]
Blocks node 8 upgrade

**Comment by vladikoff** [comment]
@deeptibaghel if you have time could you check if you can reproduce this issue in OS X or Linux with Node 8? 

(We use `nvm` to switch between node versions: https://github.com/creationix/nvm#node-version-manager--- , this will be helpful to switch like so `nvm use 6` or `nvm use 8` and test this issue)

**Comment by deeptibaghel** [comment]
@vladikoff yeah i tried this y'day on mac. It throws the error with node 8 but i had no clue about what to fix :(

**Comment by deeptibaghel** [comment]
deprecationWarning: os.tmpDir() is being thrown from a number of node modules which i could fix manually and may be upgrading those modules will make it work, should i try upgrading `asap` for the exception ?

**Comment by vladikoff** [comment]
@deeptibaghel hm i think 'tmpdir' is just a rename, we need to find the bug in linter.js I think
