### ISSUE TITLE
Broken change email circle-ci tests

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5673]
With the introduction of https://github.com/mozilla/fxa-dev/commit/6f255815e27a26b67279695f6304657f3acc6656, this broke some of the change email tests. Lets unbork them.

Ref: https://circleci.com/gh/mozilla/fxa-content-server/8658#tests/containers/1

```
× firefox on any platform - settings change email - does no show change email option if query `canChangeEmail` not set (30.526s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/3b0cec3f-d285-44a3-80f2-a2b8bea5e065/element / {"using":"css selector","value":"#emails .settings-unit-stub button"}] Unable to locate element: #emails .settings-unit-stub button
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-129-generic', java.version: '1.8.0_102'
Driver info: driver.version: unknown
  at Command.<anonymous>  <tests/functional/lib/helpers.js:184:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Test.does no show change email option if query `canChangeEmail` not set [as test]  <tests/functional/settings_change_email.js:97:10>
```

**Comment by vbudhram** [comment]
I reverted the config that broke this, will test out on a separate box (fxaci2) before changing the config.

**Comment by vbudhram** [comment]
Reopening this because change email tests are indeed broken, but it's because of https://github.com/mozilla/fxa-auth-server/pull/2194 sending a post change primary email.

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-auth-server/issues/2206
