### ISSUE TITLE
TypeError and UnhandledPromiseRejectionWarning running tests/server/routes/get-verify-email.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5677]
The tests say they pass ok, but this can't be correct.

Run this command:
`
$ ./node_modules/.bin/intern-client config=tests/intern_server fxaAuthRoot=https://api-accounts.stage.mozaws.net/v1 fxaContentRoot=https://accounts.stage.mozaws.net/ fxaOAuthRoot=https://oauth.stage.mozaws.net fxaProfileRoot=https://profile.stage.mozaws.net fxaTokenRoot=https://token.stage.mozaws.net fxaProduction=true fxaDevBox= asyncTimeout=10000 grep='verify_email'
`

Output:
```
Creating Firefox profile...
[1Jtests/intern_server
Total: Pending
Passed: 0  Failed: 0  Skipped: 0
[1Jtests/intern_server
Total: [~~~~~~\                                 ] 102/724
Passed: 0    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~|                                 ] 102/724
Passed: 0    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~/                                 ] 102/724
Passed: 0    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~-                                 ] 102/724
Passed: 0    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~\                                 ] 103/724
Passed: 1    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~|                                 ] 103/724
Passed: 1    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~/                                 ] 103/724
Passed: 1    Failed: 0    Skipped: 102

[1Jtests/intern_server
Total: [~~~~~~-                                 ] 106/724
Passed: 2    Failed: 0    Skipped: 104

[1Jtests/intern_server
Total: [~~~~~~\                                 ] 107/724
Passed: 3    Failed: 0    Skipped: 104

[1Jtests/intern_server
Total: [~~~~~~|                                 ] 107/724
Passed: 3    Failed: 0    Skipped: 104

[1Jtests/intern_server
Total: [~~~~~~/                                 ] 107/724
Passed: 3    Failed: 0    Skipped: 104

{"Timestamp":1509579138931000000,"Logger":"fxa-content-server","Type":"server.get-verify-email.TypeError: res.redirect is not a function","Severity":2,"Pid":93871,"EnvVersion":"2.0","Fields":{"stack":"\n    at got.post.then (/Users/jrgm/gitwork/fxa-content-server/fxa-content-server-stage-server/server/lib/routes/get-verify-email.js:93:24)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}}
{"Timestamp":1509579138933000000,"Logger":"fxa-content-server","Type":"server.get-verify-email.[object Object]","Severity":2,"Pid":93871,"EnvVersion":"2.0"}
{"Timestamp":1509579138934000000,"Logger":"fxa-content-server","Type":"server.get-verify-email.[object Object]","Severity":2,"Pid":93871,"EnvVersion":"2.0"}
{"Timestamp":1509579138937000000,"Logger":"fxa-content-server","Type":"server.get-verify-email.TypeError: res.redirect is not a function","Severity":2,"Pid":93871,"EnvVersion":"2.0","Fields":{"stack":"\n    at got.post.then (/Users/jrgm/gitwork/fxa-content-server/fxa-content-server-stage-server/server/lib/routes/get-verify-email.js:93:24)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}}
(node:93871) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): AssertionError: expected 0 to equal 1
(node:93871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:93871) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): AssertionError: expected 1 to equal 0
[1Jtests/intern_server
Total: [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~‚úì-   ] 635/724
Passed: 7    Failed: 0    Skipped: 628

{"Timestamp":1509579139044000000,"Logger":"fxa-content-server","Type":"server.get-verify-email.TypeError: res.redirect is not a function","Severity":2,"Pid":93871,"EnvVersion":"2.0","Fields":{"stack":"\n    at got.post.then (/Users/jrgm/gitwork/fxa-content-server/fxa-content-server-stage-server/server/lib/routes/get-verify-email.js:93:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}}
[1J‚úì front end routes - #https get https://accounts.stage.mozaws.net/v1/verify_email
‚úì front end routes - #http get http://accounts.stage.mozaws.net/v1/verify_email
‚úì front end routes - #https get https://accounts.stage.mozaws.net/verify_email
‚úì front end routes - #http get http://accounts.stage.mozaws.net/verify_email
‚úì verify_email - logs error without query params
‚úì verify_email - no logs if successful
‚úì verify_email - logs errors when post fails
‚úì verify_email - logs error with invalid utm param
‚úì verify_email - no logs with valid resume param

```

**Comment by jrgm** [comment]
Note for the future: `(node:93871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by philbooth** [comment]
Idea from the meeting: we could modify the test harness to abort the process inside an `unhandledRejection` handler, so we're forced to deal with issues like this immediately.

**Comment by jrgm** [comment]
Update to this (actually it's noted above but not easy to see in the output). It says:
`server.get-verify-email.TypeError: res.redirect is not a function`

The mock is missing a `res.redirect`: https://github.com/mozilla/fxa-content-server/blob/master/tests/server/routes/get-verify-email.js#L28-L30 for one thing.

Should really fix this test.

**Comment by vladikoff** [comment]
@jrgm good find!!

**Comment by vladikoff** [comment]
@jrgm while migrating to Intern 4 it found these issues and threw harder errors. The test needs to be refactored.  I will just fix this for train-104 with the new intern version in https://github.com/mozilla/fxa-content-server/pull/5787
