### ISSUE TITLE
Flaky functional test on Circle - Firefox Desktop Sync v3 signin - Fx >= 58, verified, does not need to confirm - control

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5757]
See https://circleci.com/gh/mozilla/fxa-content-server/8902#queue-placeholder/containers/0

> Screenshot saved at: https://screencap.co.uk/images/9e68b78ba1965dd2049ffe9a344b5fa1290a27b7.png
× firefox on any platform - Firefox Desktop Sync v3 signin - Fx >= 58, verified, does not need to confirm - control (33.568s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/f481d5fb-d1af-410e-9da7-6e6eaf7525fb/element / {"using":"css selector","value":"#fxa-signin-header"}] Unable to locate element: #fxa-signin-header
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-129-generic', java.version: '1.8.0_102'
Driver info: driver.version: unknown
  at Command.<anonymous>  <tests/functional/lib/helpers.js:155:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:166:14>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:163:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1157:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1159:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Test.Fx >= 58, verified, does not need to confirm - control [as test]  <tests/functional/sync_v3_sign_in.js:87:10>

**Comment by shane-tomlinson** [comment]
Treatment fails as often as control
