### ISSUE TITLE
Builds always fail tests for v1.106.4

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5956]
Every time fails with the below, so I can't get a docker image with which to deploy v1.106.4. Could it be that a UI change in `master`, and on fxaci, means that the current tests in `train-106` are doomed to fail? 
-> @vbudhram 

```
× firefox on linux 3.13.0-142-generic - settings/avatar - go to settings then avatar change (21.257s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/9149fb52-dff1-4311-9295-755e92cc6d90/element / {"using":"css selector","value":"#change-avatar .settings-unit-toggle.primary"}] Unable to locate element: #change-avatar .settings-unit-toggle.primary
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-142-generic', java.version: '1.8.0_102'
    Driver info: driver.version: unknown
      at Command.<anonymous>  <tests/functional/lib/helpers.js:180:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:52:23>
      at Test.go to settings then avatar change [as test]  <tests/functional/avatar.js:73:10>
      at <src/lib/Test.ts:260:47>
```

**Comment by vladikoff** [comment]
@vbudhram we need to disable that test for 106.4

**Comment by vladikoff** [comment]
> Could it be that a UI change in master, and on fxaci, means that the current tests in train-106 are doomed to fail?

Yeah exactly

**Comment by jrgm** [comment]
I can just hack that test out and tag v1.106.5. I'll try that now.

**Comment by vladikoff** [comment]
This was cleared
