### ISSUE TITLE
grunt watch:livereload excepts with `_.contains is not a function`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6092]
> ➜  fxa-content-server git:(train-109-fix-chrome) ✗ grunt watch:livereload                                 git:(train-109-fix-chrome↑1|✚2…
Running "watch:livereload" (watch) task
Waiting...
fxa-content-server.CRITICAL: uncaughtException TypeError: _.contains is not a function
  at Gaze.<anonymous> (/Users/shanetomlinson/development/fxa-content-server/node_modules/grunt-contrib-watch/tasks/watch.js:138:18)
  at emitTwo (events.js:106:13)
  at Gaze.emit (events.js:191:7)
  at Gaze.emit (/Users/shanetomlinson/development/fxa-content-server/node_modules/gaze/lib/gaze.js:129:32)
  at /Users/shanetomlinson/development/fxa-content-server/node_modules/gaze/lib/gaze.js:437:16
  at StatWatcher._pollers.(anonymous function) (/Users/shanetomlinson/development/fxa-content-server/node_modules/gaze/lib/gaze.js:345:7)
  at emitTwo (events.js:106:13)
  at StatWatcher.emit (events.js:191:7)
  at StatWatcher._handle.onchange (fs.js:1509:10)

**Comment by shama** [comment]
Weird, I'll check on it.

**Comment by shama** [comment]
It looks like it was using `lodash@4` where inside the watch task, it was still using `lodash@3` (and `_.contains` was changed to `_.includes`.

I published a new version of `grunt-contrib-watch` with lodash updated. So doing another `npm install` should fix it.

**Comment by vladikoff** [comment]
@shama 🚤 Yesssss

**Comment by shane-tomlinson** [comment]
Thank you @shama!
