### ISSUE TITLE
Teamcity: Two failing functional tests against stage

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6251]
>  authorization with email (trusted)  

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/e7d119c0-fafc-4594-ae2f-d2ad10ad6518/element / {"using":"css selector","value":"#fxa-signup-header"}] Unable to locate element: #fxa-signup-header For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z' System info: host: 'c70b0351e646', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144' Driver info: driver.version: unknown at Command.<anonymous> <tests/functional/lib/helpers.js:156:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:167:12> at Command.<anonymous> <tests/functional/lib/helpers.js:164:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1243:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1245:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/oauth_query_param_validation.js:53:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Test.authorization with email (trusted) [as test] <tests/functional/oauth_query_param_validation.js:368:10> at <src/lib/Test.ts:260:47>

---------------

> oauth endpoint chooses the right auth flows 

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/e7d119c0-fafc-4594-ae2f-d2ad10ad6518/element / {"using":"css selector","value":"#fxa-signin-header"}] Unable to locate element: #fxa-signin-header For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z' System info: host: 'c70b0351e646', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144' Driver info: driver.version: unknown at Command.<anonymous> <tests/functional/lib/helpers.js:156:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:167:12> at Command.<anonymous> <tests/functional/lib/helpers.js:164:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Test.oauth endpoint chooses the right auth flows [as test] <tests/functional/oauth_sign_in.js:197:10> at <src/lib/Test.ts:260:47>

**Comment by shane-tomlinson** [comment]
Dup of #6250, closing.
