### ISSUE TITLE
Failing server test: "Expected 404 to be 200"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6330]
> Unhandled rejection: { AssertionError: expected 404 to equal 200
    at /Users/shanetomlinson/development/fxa-content-server/tests/server/helpers/routesHelpers.js:161:20
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'expected 404 to equal 200',
  showDiff: true,
  actual: 404,
  expected: 200 } Promise {
  <rejected> { AssertionError: expected 404 to equal 200
    at /Users/shanetomlinson/development/fxa-content-server/tests/server/helpers/routesHelpers.js:161:20
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'expected 404 to equal 200',
  showDiff: true,
  actual: 404,
  expected: 200 } }

First saw in https://travis-ci.org/mozilla/fxa-content-server/builds/399735652, then in https://travis-ci.org/mozilla/fxa-content-server/builds/399868589

blocks #6327 
blocks #6329

**Comment by shane-tomlinson** [comment]
Applying this patch, I see some unexpected results:

```diff
diff --git a/tests/server/helpers/routesHelpers.js b/tests/server/helpers/routesHelpers.js
index 399ae9699..2ac8dd4cc 100644
--- a/tests/server/helpers/routesHelpers.js
+++ b/tests/server/helpers/routesHelpers.js
@@ -158,7 +158,7 @@ function checkUrls(origin, resources) {
               return;
             }
 
-            assert.equal(res.statusCode, 200);
+            assert.equal(res.statusCode, 200, resource.url);
 
             // If prod-like, Check all CSS and JS (except experiments.bundle.js)
             // for SRI `integrity=` attribute on the link, and that the checksum
```

> Unhandled rejection: { AssertionError: https://firefox-source-docs.mozilla.org/mobile/android/fennec/index.html: expected 404 to equal 200

**Comment by shane-tomlinson** [comment]
In /legal/privacy the Desktop and Android "Telemetry" links both 404 - search for:

```
Read the telemetry documentation for Desktop, Android, or iOS or learn how to opt-out of this data collection.
```

**Comment by shane-tomlinson** [comment]
This link needs to be: https://firefox-source-docs.mozilla.org/mobile/android/docs/fennec/index.html
