### ISSUE TITLE
Make sure v1.116.2 builds a tag

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6368]
Tests on Circle are spazzing out hard

**Comment by vladikoff** [comment]
ref https://github.com/mozilla/fxa-content-server/pull/6366

**Comment by vladikoff** [comment]
This test doesn't even:

```
Screenshot saved at: https://screencap.co.uk/images/dbfb11867c464e0ff68df72beddcdb454a37d841.png
× firefox on linux 3.13.0-151-generic - Firefox Desktop Sync v3 reset password - reset password, verify same browser, Fx <= 57 (11.262s)
    Error: NoSuchBrowserNotification
      at Command.parent.then.then  <tests/functional/lib/helpers.js:1635:45>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1633:12>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1630:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:57:23>
      at Command.<anonymous>  <tests/functional/sync_v3_reset_password.js:62:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:57:23>
      at Test.reset password, verify same browser, Fx <= 57 [as test]  <tests/functional/sync_v3_reset_password.js:85:10>
      at <src/lib/Test.ts:260:47>
```
