### ISSUE TITLE
[Train 118] Sync not working on Android P

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6428]
Environment:
Stage server - Train 118
Device: Google Pixel (Android 9)

STR:
1. Log in with the same account on Android and Desktop;
2. Make some browsing history, bookmark a few pages;
3. Go to settings and perform a sync.

Actual results:
Sync is not working, no data was displayed on mobile or desktop. On mobile "Last synced: never" never don't get updated and also the "Choose what to sync " section is greyed out. 

Expected results:
All of the new data created while browsing on mobile should now be on desktop side. And the same results for desktop-mobile.

Not reproducible with Samsung Galaxy Note8(Android 8.0.0), Nokia 6(Android 7.1.1), iPhone SE(11.0.1).

[log.AndroidP.txt](https://github.com/mozilla/fxa-content-server/files/2277909/log.AndroidP.txt)

**Comment by ncalexan** [comment]
I see
```
08-10 15:07:58.379: I/FxAccounts(22128): firefox :: LoginStateMachineDelegate :: Fetching profile avatar information.
08-10 15:07:58.384: E/FxAccounts(22128): firefox :: FxAccountSyncAdapter :: Failed to get token.
08-10 15:07:58.384: E/FxAccounts(22128): javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
08-10 15:07:58.384: E/FxAccounts(22128): 	at ch.boye.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:308)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.sync.net.BaseResource.retryRequest(BaseResource.java:349)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:318)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:373)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.sync.net.BaseResource.get(BaseResource.java:379)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.tokenserver.TokenServerClient.getTokenFromBrowserIDAssertion(TokenServerClient.java:329)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter.syncWithAssertion(FxAccountSyncAdapter.java:470)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter$3.handleMarried(FxAccountSyncAdapter.java:720)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.fxa.authenticator.FxADefaultLoginStateMachineDelegate.handleFinal(FxADefaultLoginStateMachineDelegate.java:81)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine$ExecuteDelegate.handleTransition(FxAccountLoginStateMachine.java:64)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:46)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:28)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.background.fxa.FxAccountClient20$5.handleSuccess(FxAccountClient20.java:579)
08-10 15:07:58.384: E/FxAccounts(22128): 	at org.mozilla.gecko.background.fxa.FxAccountClient20$ResourceDelegate$2.run(FxAccountClient20.java:279)
08-10 15:07:58.384: E/FxAccounts(22128): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-10 15:07:58.384: E/FxAccounts(22128): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-10 15:07:58.384: E/FxAccounts(22128): 	at java.lang.Thread.run(Thread.java:764)
08-10 15:07:58.384: E/FxAccounts(22128): Caused by: java.security.cert.CertificateException: java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:412)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
08-10 15:07:58.384: E/FxAccounts(22128): 	... 26 more
08-10 15:07:58.384: E/FxAccounts(22128): Caused by: java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot
08-10 15:07:58.384: E/FxAccounts(22128): 	at javax.net.ssl.SNIHostName.checkHostName(SNIHostName.java:319)
08-10 15:07:58.384: E/FxAccounts(22128): 	at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:108)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.Platform.getSSLParameters(Platform.java:140)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getSSLParameters(ConscryptFileDescriptorSocket.java:1099)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:337)
08-10 15:07:58.384: E/FxAccounts(22128): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
08-10 15:07:58.384: E/FxAccounts(22128): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
08-10 15:07:58.384: E/FxAccounts(22128): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
08-10 15:07:58.384: E/FxAccounts(22128): 	... 29 more
08-10 15:07:58.385: D/GeckoLogger(22128): Thread with tag and thread id releasing lock: FxAccountSyncAdapter, 451 ...
```
and
```
08-10 15:08:00.122: E/GeckoLogger(22128): firefox :: FxAccountAuthenticator :: OAuth failure.
08-10 15:08:00.122: E/GeckoLogger(22128): <FxAccountAbstractClientRemoteException 401 [104]: Invalid assertion>
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountAbstractClient.validateResponse(FxAccountAbstractClient.java:110)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountAbstractClient$ResourceDelegate.handleHttpResponse(FxAccountAbstractClient.java:169)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:342)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:373)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.post(BaseResource.java:404)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.post(BaseResource.java:537)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountAbstractClient.post(FxAccountAbstractClient.java:127)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountOAuthClient10.authorization(FxAccountOAuthClient10.java:100)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator$1.handleMarried(FxAccountAuthenticator.java:218)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator$FxADefaultLoginStateMachineDelegate.handleFinal(FxAccountAuthenticator.java:172)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine.advance(FxAccountLoginStateMachine.java:78)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator.getOAuthToken(FxAccountAuthenticator.java:194)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator.getAuthToken(FxAccountAuthenticator.java:280)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:247)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:114)
08-10 15:08:00.122: E/GeckoLogger(22128): 	at android.os.Binder.execTransact(Binder.java:731)
08-10 15:08:00.122: E/GeckoLogger(22128): Caused by: <HTTPFailureException 401 :: ([unknown error message])>
08-10 15:08:00.122: E/GeckoLogger(22128): 	... 16 more
08-10 15:08:00.125: I/GeckoLogger(22128): firefox :: AndroidFxAccount :: Moving account named like XXXX@XXXXXXXXXX.XXX to state Cohabiting
08-10 15:08:00.138: W/GeckoLogger(22128): firefox :: FxAccountAuthenticator :: Responding with error!
08-10 15:08:00.138: W/GeckoLogger(22128): <FxAccountAbstractClientRemoteException 401 [104]: Invalid assertion>
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountAbstractClient.validateResponse(FxAccountAbstractClient.java:110)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountAbstractClient$ResourceDelegate.handleHttpResponse(FxAccountAbstractClient.java:169)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:342)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:373)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.post(BaseResource.java:404)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.sync.net.BaseResource.post(BaseResource.java:537)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountAbstractClient.post(FxAccountAbstractClient.java:127)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.background.fxa.oauth.FxAccountOAuthClient10.authorization(FxAccountOAuthClient10.java:100)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator$1.handleMarried(FxAccountAuthenticator.java:218)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator$FxADefaultLoginStateMachineDelegate.handleFinal(FxAccountAuthenticator.java:172)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine.advance(FxAccountLoginStateMachine.java:78)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator.getOAuthToken(FxAccountAuthenticator.java:194)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at org.mozilla.gecko.fxa.authenticator.FxAccountAuthenticator.getAuthToken(FxAccountAuthenticator.java:280)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:247)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:114)
08-10 15:08:00.138: W/GeckoLogger(22128): 	at android.os.Binder.execTransact(Binder.java:731)
08-10 15:08:00.138: W/GeckoLogger(22128): Caused by: <HTTPFailureException 401 :: ([unknown error message])>
08-10 15:08:00.138: W/GeckoLogger(22128): 	... 16 more
08-10 15:08:00.138: D/GeckoLogger(22128): Thread with tag and thread id releasing lock: FxAccountAuthenticator, 453 ...
08-10 15:08:00.138: D/GeckoLogger(22128): Thread with tag and thread id releasing lock: FxAccountAuthenticator, 453 ... RELEASED
08-10 15:08:00.143: E/GeckoLogger(22128): firefox :: AndroidFxAccount :: Error fetching profile information; ignoring.
08-10 15:08:00.143: E/GeckoLogger(22128): android.accounts.AuthenticatorException: <FxAccountAbstractClientRemoteException 401 [104]: Invalid assertion>
08-10 15:08:00.143: E/GeckoLogger(22128): 	at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2523)
08-10 15:08:00.143: E/GeckoLogger(22128): 	at android.accounts.AccountManager.access$700(AccountManager.java:166)
08-10 15:08:00.143: E/GeckoLogger(22128): 	at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2359)
08-10 15:08:00.143: E/GeckoLogger(22128): 	at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:70)
08-10 15:08:00.143: E/GeckoLogger(22128): 	at android.os.Binder.execTransact(Binder.java:731)
08-10 15:08:00.168: I/FxADeviceRegistrator(22128): Push registration succeeded. Beginning normal FxA Registration.
```

This could be:
- a server/certificate configuration issue
- a Fennec certificate/crypto coding error
- something else entirely

Given that we got a network error _and_ a network success with a rejected malformed assertion, I think the most likely is a token server configuration error.

**Comment by ncalexan** [comment]
We should take this to Bugzilla, I think.

**Comment by SorinaFlorean** [comment]
Filed bug 1482789.
