### ISSUE TITLE
Users see an error if visiting /confirm_reset_password without initiating a password_reset

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6724]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=45284&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests#testNameId-5055117668506393902

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/87c89ec0-21d9-469c-a314-bbbe9837cfb6/element / {"using":"css selector","value":"#fxa-reset-password-header"}] Unable to locate element: #fxa-reset-password-header For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z' System info: host: 'a4da6ae44c9f', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144' Driver info: driver.version: unknown at Command.<anonymous> <tests/functional/lib/helpers.js:166:6> at Command.<anonymous> <tests/functional/lib/helpers.js:59:23> at Command.<anonymous> <tests/functional/lib/helpers.js:72:18> at Command.<anonymous> <tests/functional/lib/helpers.js:67:10> at Command.<anonymous> <tests/functional/lib/helpers.js:1219:6> at Command.<anonymous> <tests/functional/lib/helpers.js:59:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1221:6> at Command.<anonymous> <tests/functional/lib/helpers.js:59:23> at Command.<anonymous> <tests/functional/lib/helpers.js:67:10> at Test.visit confirmation screen without initiating reset_password, user is redirected to /reset_password [as test] <tests/functional/reset_password.js:125:10> at <src/lib/Test.ts:263:51>

**Comment by shane-tomlinson** [comment]
We've had 2 passes in a row, I'm optimistically closing this until it appears again.

**Comment by shane-tomlinson** [comment]
This was a premature closure, [it's happened again](https://tc-test.dev.lcip.org/viewLog.html?buildId=45362&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests).

**Comment by shane-tomlinson** [comment]
From this screen shot, it's claiming the `email` query param is missing.

![6fa57fd1b6077b073d1978ccaca85a99c8a3cad0](https://user-images.githubusercontent.com/848085/49097042-d8560400-f263-11e8-832e-76ba83e75899.png)
